import { createElement } from 'lwc';
import { getRecord, notifyRecordUpdateAvailable } from 'lightning/uiRecordApi';
import { ShowToastEventName } from 'lightning/platformShowToastEvent';
import submitForApproval from '@salesforce/apex/OpportunityApprovalController.submitForApproval';

import DiscountApprovalPanel from 'c/discountApprovalPanel';

/**
 * discountApprovalPanel Jest suite - build northwind-sales, step M3-S04.
 *
 * Harness copied from skills/lwc/lwc-testing/references/code-examples.md and
 * skills/lwc/wire-service-patterns/references/code-examples.md section 5. Two rules from
 * skills/lwc/lwc-base-component-recipes govern every assertion below:
 *
 *   1. The sfdx-lwc-jest `lightning-stubs` "match the API of the actual components but
 *      don't have all the functionality" and fire no events of their own
 *      (lwc_guide L12622, L12627) - so interaction is simulated by calling click() or
 *      dispatchEvent() at the stub.
 *   2. "Not every property is reflected as a DOM attribute" (L12626) - so every assertion
 *      reads a PROPERTY off the stub (`button.disabled`, `form.recordId`) and never
 *      getAttribute(), which would return null on a passing and a failing component alike.
 *
 * The four button-state cases below are the step's manual acceptance test, in its words:
 * disabled at a discount of 20, enabled at 25 with no approval status, disabled at 25 with
 * Pending, disabled at 25 with Approved. They pin Q35 in both directions rather than only
 * on the happy path.
 */

// `@salesforce/apex/...` is generated by the LWC compiler and has no file on disk, so
// { virtual: true } is mandatory or Jest throws "Cannot find module" while collecting.
jest.mock(
    '@salesforce/apex/OpportunityApprovalController.submitForApproval',
    () => ({ default: jest.fn() }),
    { virtual: true }
);

// getRecord keeps its stock test wire adapter (that is where .emit() comes from); only
// notifyRecordUpdateAvailable is replaced, so the refresh call can be asserted. Replacing
// the whole module would throw the adapter away - skills/lwc/lwc-testing/references/
// llm-anti-patterns.md, "Mocking the module the component does not import".
jest.mock('lightning/uiRecordApi', () => {
    const actual = jest.requireActual('lightning/uiRecordApi');
    return { ...actual, notifyRecordUpdateAvailable: jest.fn(() => Promise.resolve()) };
});

const RECORD_ID = '006xx0000000001AAA';

/**
 * A trimmed UI API record response. Discount__c is written as the plain number (25 for 25%),
 * which is assumption A35's unverified half - the formula half of the same build writes
 * 0.20. If a retrieved record proves the UI API returns the fraction instead, these two
 * literals and the component's threshold are what change, and this suite is what fails first.
 */
function opportunityRecord(discount, approvalStatus) {
    return {
        apiName: 'Opportunity',
        id: RECORD_ID,
        fields: {
            Discount__c: {
                displayValue: discount === null ? null : `${discount}%`,
                value: discount
            },
            Approval_Status__c: {
                displayValue: approvalStatus,
                value: approvalStatus
            }
        }
    };
}

function build(props = {}) {
    const element = createElement('c-discount-approval-panel', {
        is: DiscountApprovalPanel
    });
    // Properties set BEFORE appendChild render synchronously (lwc_guide L12505-L12506).
    Object.assign(element, { recordId: RECORD_ID }, props);
    document.body.appendChild(element);
    return element;
}

/** One awaited microtask per re-render; four covers click -> Apex -> refresh -> render. */
async function settle() {
    for (let i = 0; i < 4; i += 1) {
        await Promise.resolve();
    }
}

function submitButton(element) {
    return element.shadowRoot.querySelector('[data-id="submit"]');
}

function outcomeText(element) {
    return element.shadowRoot.querySelector('[data-id="outcome"]').textContent;
}

describe('c-discount-approval-panel', () => {
    afterEach(() => {
        // One jsdom instance is shared across the file and is not reset between tests, so
        // anything left mounted leaks forward (lwc_guide L12362-L12363).
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
        jest.clearAllMocks();
    });

    describe('the Submit button state (Q35)', () => {
        it('is disabled at a discount of 20 - equal to the threshold is not above it', async () => {
            const element = build();
            // The component receives wire updates only once connected, so emit AFTER
            // appendChild (lwc_guide L12548).
            getRecord.emit(opportunityRecord(20, null));
            await Promise.resolve();

            expect(submitButton(element).disabled).toBe(true);
        });

        it('is enabled at a discount of 25 with no approval status yet', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            expect(submitButton(element).disabled).toBe(false);
        });

        it('is disabled at a discount of 25 when Approval_Status__c is Pending', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(25, 'Pending'));
            await Promise.resolve();

            expect(submitButton(element).disabled).toBe(true);
        });

        it('is disabled at a discount of 25 when Approval_Status__c is Approved', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(25, 'Approved'));
            await Promise.resolve();

            expect(submitButton(element).disabled).toBe(true);
        });

        it('is enabled again at a discount of 25 after a Rejected outcome', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(25, 'Rejected'));
            await Promise.resolve();

            // Restricted picklist values are Pending / Approved / Rejected; only the first
            // two block a submission, so a rejected deal can be re-submitted.
            expect(submitButton(element).disabled).toBe(false);
        });

        it('is disabled before the wire emits, because an unevaluated rule is closed', () => {
            const element = build();

            expect(submitButton(element).disabled).toBe(true);
        });

        it('reads the discountThreshold design attribute, which App Builder hands over as a string', async () => {
            const element = build({ discountThreshold: '30' });
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            // 25 is above the default 20 but not above 30. An uncoerced '30' would make
            // 25 > '30' false as well, so the hint is asserted too: it proves the number
            // reached the template rather than the string.
            expect(submitButton(element).disabled).toBe(true);
            expect(element.shadowRoot.querySelector('[data-id="hint"]').textContent).toContain(
                'above 30%'
            );
        });
    });

    describe('reading the record', () => {
        it('renders both fields as direct children of the record view form', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(25, 'Pending'));
            await Promise.resolve();

            const form = element.shadowRoot.querySelector('lightning-record-view-form');
            expect(form.recordId).toBe(RECORD_ID);
            expect(form.objectApiName).toBe('Opportunity');

            const fields = element.shadowRoot.querySelectorAll('lightning-output-field');
            expect(fields).toHaveLength(2);
            // lightning-output-field renders nothing unless it is a direct child of the
            // form (lwc_guide L11727).
            fields.forEach((field) => expect(field.parentElement).toBe(form));
        });

        it('explains the closed button and shows an alert when the wire errors', async () => {
            const element = build();
            getRecord.error({ body: { message: 'Insufficient access' }, status: 403 });
            await Promise.resolve();

            const alert = element.shadowRoot.querySelector('[data-id="record-error"]');
            expect(alert).not.toBeNull();
            expect(alert.getAttribute('role')).toBe('alert');
            expect(alert.textContent).toContain('Insufficient access');
            expect(submitButton(element).disabled).toBe(true);
        });

        it('carries a polite live region that is present before anything is announced', () => {
            const element = build();

            const region = element.shadowRoot.querySelector('[data-id="outcome"]');
            expect(region).not.toBeNull();
            expect(region.getAttribute('role')).toBe('status');
            expect(region.getAttribute('aria-live')).toBe('polite');
            expect(region.getAttribute('tabindex')).toBe('-1');
        });
    });

    describe('submitting', () => {
        it('calls the controller, announces the outcome, refreshes the record and moves focus', async () => {
            submitForApproval.mockResolvedValue({
                opportunityId: RECORD_ID,
                success: true,
                message: null,
                instanceStatus: 'Pending'
            });

            const element = build();
            const toastHandler = jest.fn();
            element.addEventListener(ShowToastEventName, toastHandler);
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            submitButton(element).click();
            await settle();

            expect(submitForApproval).toHaveBeenCalledTimes(1);
            expect(submitForApproval).toHaveBeenCalledWith({ opportunityId: RECORD_ID });
            expect(outcomeText(element)).toContain('Pending');
            expect(toastHandler.mock.calls[0][0].detail.variant).toBe('success');
            // The stale read is a UI API wire, so the refresh is
            // notifyRecordUpdateAvailable([{ recordId }]) and never refreshApex.
            expect(notifyRecordUpdateAvailable).toHaveBeenCalledWith([{ recordId: RECORD_ID }]);
            expect(element.shadowRoot.activeElement).toBe(
                element.shadowRoot.querySelector('[data-id="outcome"]')
            );
        });

        it('treats a returned success=false as a failure, with no record refresh', async () => {
            // Q30's shape: the service refuses by RETURNING an outcome, not by throwing.
            submitForApproval.mockResolvedValue({
                opportunityId: RECORD_ID,
                success: false,
                message: 'ALREADY_IN_PROCESS: This record is currently in an approval process.',
                instanceStatus: null
            });

            const element = build();
            const toastHandler = jest.fn();
            element.addEventListener(ShowToastEventName, toastHandler);
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            submitButton(element).click();
            await settle();

            expect(outcomeText(element)).toContain('ALREADY_IN_PROCESS');
            expect(toastHandler.mock.calls[0][0].detail.variant).toBe('error');
            expect(notifyRecordUpdateAvailable).not.toHaveBeenCalled();
        });

        it('says so when the outcome is a refusal carrying no message', async () => {
            submitForApproval.mockResolvedValue({
                opportunityId: RECORD_ID,
                success: false,
                message: null,
                instanceStatus: null
            });

            const element = build();
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            submitButton(element).click();
            await settle();

            expect(outcomeText(element)).toContain('no reason was returned');
        });

        it('renders the message when the Apex call itself rejects', async () => {
            // Apex read and write errors carry body as an OBJECT (lwc_guide L6570).
            submitForApproval.mockRejectedValue({
                body: { message: 'FIELD_CUSTOM_VALIDATION_EXCEPTION' }
            });

            const element = build();
            const toastHandler = jest.fn();
            element.addEventListener(ShowToastEventName, toastHandler);
            getRecord.emit(opportunityRecord(25, null));
            await Promise.resolve();

            submitButton(element).click();
            await settle();

            expect(outcomeText(element)).toContain('FIELD_CUSTOM_VALIDATION_EXCEPTION');
            expect(toastHandler.mock.calls[0][0].detail.variant).toBe('error');
            expect(notifyRecordUpdateAvailable).not.toHaveBeenCalled();
        });

        it('does not call Apex while the button is disabled', async () => {
            const element = build();
            getRecord.emit(opportunityRecord(20, null));
            await Promise.resolve();

            // The stub has no behaviour, so click() calls straight through a disabled
            // button - which is exactly why the handler guards on isSubmitDisabled.
            submitButton(element).click();
            await settle();

            expect(submitForApproval).not.toHaveBeenCalled();
        });
    });
});
