#!/usr/bin/env python3
"""Static checks for Custom Report Type metadata.

Scans ``reportTypes/*.reportType-meta.xml`` (sfdx-style metadata) for issues
documented in ``references/gotchas.md`` and ``references/metadata-examples.md``.

Per-file checks
---------------
ERROR
  * More than four objects in the join chain. Metadata API Developer Guide,
    ``ObjectRelationship``: "A maximum of four objects can be joined in a
    custom report type."
  * An inner join placed after an outer join. Same section: "When more than
    two objects are joined, an inner join isn't allowed if there has been an
    outer join earlier in the join sequence."

WARN
  * A ``<sections>`` element with no ``<columns>``. ``masterLabel`` is required
    on ReportLayoutSection while ``columns`` is not, so an empty section
    deploys cleanly and produces a named, empty field group.
  * A ``<sections>`` element with no ``<masterLabel>`` (the guide marks it
    Required).
  * More than 60 columns with ``checkedByDefault`` true (display-limit risk).
  * More than 200 columns in total (curation issue).
  * Missing or terse ``<description>`` — it is what the report builder shows.
  * No ``<sections>`` at all (flat, unscannable layout).

INFO
  * ``<deployed>false</deployed>`` — the type is invisible to anyone without
    Manage Custom Report Types.

Cross-file checks
-----------------
WARN
  * Two report types sharing the same ``<label>``.
INFO
  * Two report types sharing the same ``baseObject`` and the same join
    topology — possible sprawl.

Autogenerated report types (``<autogenerated>true</autogenerated>``) are
skipped: the guide describes them as created automatically when historical
trending is enabled for an entity, so they are not authored artifacts.

Stdlib only — uses xml.etree.ElementTree.

Usage:
    python3 check_report_type_strategy.py --manifest-dir force-app/main/default
"""

from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from collections import defaultdict
from pathlib import Path

_NS = "http://soap.sforce.com/2006/04/metadata"

MAX_JOINED_OBJECTS = 4
MAX_CHECKED_BY_DEFAULT = 60
MAX_TOTAL_COLUMNS = 200
MIN_DESCRIPTION_CHARS = 20


def _strip_ns(tag: str) -> str:
    return tag.split("}", 1)[1] if "}" in tag else tag


def _child(element, name):
    """Return the first direct child named `name`, or None.

    Written as an explicit loop with an `is not None` result on purpose: an
    ElementTree element with no children is falsy, so `a.find(x) or a.find(y)`
    silently discards real leaf elements.
    """
    if element is None:
        return None
    for candidate in element:
        if _strip_ns(candidate.tag) == name:
            return candidate
    return None


def _children(element, name):
    if element is None:
        return []
    return [c for c in element if _strip_ns(c.tag) == name]


def _text(element, name, default=""):
    node = _child(element, name)
    if node is None:
        return default
    return (node.text or "").strip()


def _bool(element, name):
    return _text(element, name).lower() == "true"


def _join_chain(root):
    """Return the join sequence as [(relationship, outer_join_bool), ...].

    The guide: the baseObject is joined to `relationship` first, then the
    resulting dataset is joined with whatever the nested `join` names. So the
    outermost <join> element is join #1 and each nested <join> is the next.
    """
    chain = []
    node = _child(root, "join")
    seen = 0
    while node is not None and seen < 32:  # guard against a malformed cycle
        chain.append((_text(node, "relationship", "(unnamed)"), _bool(node, "outerJoin")))
        node = _child(node, "join")
        seen += 1
    return chain


class ReportTypeFile:
    def __init__(self, path: Path, root):
        self.path = path
        self.full_name = path.name.split(".")[0]
        self.label = _text(root, "label", self.full_name)
        self.base_object = _text(root, "baseObject", "(missing)")
        self.description = _text(root, "description")
        self.deployed = _bool(root, "deployed")
        self.autogenerated = _bool(root, "autogenerated")
        self.chain = _join_chain(root)
        self.sections = _children(root, "sections")

    @property
    def topology(self) -> str:
        legs = [f"{rel}:{'outer' if outer else 'inner'}" for rel, outer in self.chain]
        return f"{self.base_object} -> " + (" -> ".join(legs) if legs else "(no join)")


def _scan_file(path: Path):
    """Return (findings, ReportTypeFile | None)."""
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError) as exc:
        return [("ERROR", f"{path}: parse error — {exc}")], None

    if _strip_ns(root.tag) != "ReportType":
        return [], None

    rt = ReportTypeFile(path, root)
    if rt.autogenerated:
        return [], None

    findings = []
    where = f"{path}: ReportType `{rt.label}`"

    # --- ERROR: more than four objects in the join chain -------------------
    joined_objects = 1 + len(rt.chain)
    if joined_objects > MAX_JOINED_OBJECTS:
        findings.append((
            "ERROR",
            f"{where} joins {joined_objects} objects ({rt.topology}) — the "
            f"Metadata API guide caps a custom report type at "
            f"{MAX_JOINED_OBJECTS} joined objects. Move any lookup parents out "
            "of the chain into dotted `field` paths, or split the type "
            "(references/gotchas.md § 14)",
        ))

    # --- ERROR: inner join after an outer join -----------------------------
    seen_outer_at = None
    for index, (relationship, outer) in enumerate(rt.chain, start=1):
        if outer:
            if seen_outer_at is None:
                seen_outer_at = (index, relationship)
        elif seen_outer_at is not None:
            prior_index, prior_rel = seen_outer_at
            findings.append((
                "ERROR",
                f"{where} places an inner join (#{index} `{relationship}`) "
                f"after an outer join (#{prior_index} `{prior_rel}`) — the "
                "guide states an inner join isn't allowed if there has been an "
                "outer join earlier in the join sequence. Order mandatory "
                "relationships before optional ones, or split into two report "
                "types (references/metadata-examples.md § 2)",
            ))
            break

    # --- Section-level checks ---------------------------------------------
    total_columns = 0
    checked_columns = 0
    for section in rt.sections:
        master_label = _text(section, "masterLabel")
        columns = _children(section, "columns")
        total_columns += len(columns)
        checked_columns += sum(1 for c in columns if _bool(c, "checkedByDefault"))
        section_name = master_label or "(no masterLabel)"
        if not columns:
            findings.append((
                "WARN",
                f"{where} has a section `{section_name}` with zero <columns> — "
                "it deploys cleanly and shows report authors an empty named "
                "field group. Delete the section rather than emptying it "
                "(references/gotchas.md § 15)",
            ))
        if not master_label:
            findings.append((
                "WARN",
                f"{where} has a <sections> element with no <masterLabel>, "
                "which the guide marks Required",
            ))

    if checked_columns > MAX_CHECKED_BY_DEFAULT:
        findings.append((
            "WARN",
            f"{where} pre-selects {checked_columns} columns via "
            f"checkedByDefault (>{MAX_CHECKED_BY_DEFAULT}) — past 60 fields the "
            "report builder gates them behind search "
            "(references/gotchas.md § 2)",
        ))

    if total_columns > MAX_TOTAL_COLUMNS:
        findings.append((
            "WARN",
            f"{where} exposes {total_columns} total columns — a curated type is "
            "typically under 50; consider removing rarely-used fields "
            "(references/llm-anti-patterns.md § 4)",
        ))

    if len(rt.description) < MIN_DESCRIPTION_CHARS:
        findings.append((
            "WARN",
            f"{where} has a missing or terse description "
            f"({len(rt.description)} chars) — the description is what the "
            "report-builder picker shows; say what the type excludes "
            "(references/examples.md § 6)",
        ))

    if not rt.sections:
        findings.append((
            "WARN",
            f"{where} has no <sections> grouping — flat layouts are "
            "unscannable (references/llm-anti-patterns.md § 4)",
        ))

    # --- INFO: not deployed ------------------------------------------------
    if not rt.deployed:
        findings.append((
            "INFO",
            f"{where} has deployed=false — visible only to users with Manage "
            "Custom Report Types. Reports on it keep running for admins and "
            "dashboards and are invisible to everyone else "
            "(references/gotchas.md § 10)",
        ))

    return findings, rt


def _cross_file_findings(report_types):
    findings = []

    by_label = defaultdict(list)
    for rt in report_types:
        by_label[rt.label].append(rt)
    for label, group in sorted(by_label.items()):
        if len(group) > 1:
            names = ", ".join(sorted(rt.full_name for rt in group))
            findings.append((
                "WARN",
                f"duplicate label `{label}` on {len(group)} report types "
                f"({names}) — report authors pick from labels, so two types "
                "with one label are indistinguishable in the picker",
            ))

    by_topology = defaultdict(list)
    for rt in report_types:
        by_topology[rt.topology].append(rt)
    for topology, group in sorted(by_topology.items()):
        if len(group) > 1:
            names = ", ".join(sorted(rt.full_name for rt in group))
            findings.append((
                "INFO",
                f"{len(group)} report types share baseObject and join topology "
                f"`{topology}` ({names}) — possible sprawl. Extend one type's "
                "sections instead of maintaining near-clones, and confirm "
                "usage before deleting (references/gotchas.md § 16)",
            ))

    return findings


def scan_tree(root: Path):
    if not root.exists():
        return [("ERROR", f"manifest-dir does not exist: {root}")]
    if not root.is_dir():
        return [("ERROR", f"manifest-dir is not a directory: {root}")]

    findings = []
    report_types = []
    seen_paths = set()
    for pattern in ("*.reportType-meta.xml", "*.reportType"):
        for path in sorted(root.rglob(pattern)):
            if path in seen_paths:
                continue
            seen_paths.add(path)
            file_findings, rt = _scan_file(path)
            findings.extend(file_findings)
            if rt is not None:
                report_types.append(rt)

    findings.extend(_cross_file_findings(report_types))
    return findings


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Scan Salesforce reportType metadata for report-type strategy "
            "issues: join chains over four objects, an inner join after an "
            "outer join, empty sections, undeployed types, duplicate labels, "
            "and duplicate base-object/topology pairs."
        ),
    )
    parser.add_argument(
        "--manifest-dir", "--src-root", dest="manifest_dir", default=".",
        help="Root of the metadata source tree (default: current directory).",
    )
    args = parser.parse_args()

    findings = scan_tree(Path(args.manifest_dir))

    if not findings:
        print("OK: no Report Type strategy issues detected.")
        return 0

    order = {"ERROR": 0, "WARN": 1, "INFO": 2}
    findings.sort(key=lambda item: order.get(item[0], 3))

    for severity, message in findings:
        stream = sys.stdout if severity == "INFO" else sys.stderr
        print(f"{severity}: {message}", file=stream)

    counts = {level: sum(1 for s, _ in findings if s == level)
              for level in ("ERROR", "WARN", "INFO")}
    print(
        f"\n{len(findings)} finding(s): "
        f"{counts['ERROR']} ERROR, {counts['WARN']} WARN, {counts['INFO']} INFO.",
        file=sys.stderr,
    )

    if counts["ERROR"] or counts["WARN"]:
        return 1
    return 0


if __name__ == "__main__":
    if main() != 0:
        sys.exit(1)
    sys.exit(0)
