#!/usr/bin/env python3
"""Generate human-readable API references from canonical JSON contracts."""
from __future__ import annotations

import argparse
import json
import tempfile
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]


def load_many(directory: str) -> list[dict[str, Any]]:
    return [json.loads(path.read_text(encoding="utf-8")) for path in sorted((ROOT / directory).glob("*.json"))]


def bullets(values: list[str], indent: str = "") -> list[str]:
    return [f"{indent}- {value}" for value in values]


def json_block(value: Any) -> list[str]:
    return ["```json", json.dumps(value, indent=2, sort_keys=True), "```"]


def command_reference() -> str:
    lines = [
        "# SfSkills V2 command API reference",
        "",
        "Generated from `commands/specs/*.json`. Do not edit this file directly.",
        "",
        "Commands are stable user entrypoints. Host adapters may render them differently, but must preserve validation, authority, statuses, orchestration, and side-effect contracts.",
        "",
    ]
    for item in load_many("commands/specs"):
        lines += [f"## `/{item['id']}`", "", item["purpose"], ""]
        lines += [f"- **Version:** `{item['version']}`", f"- **Product:** `{item.get('product_id') or 'framework'}`", f"- **Host visibility:** `{item['host_visibility']}`", f"- **Independent review:** `{str(item['requires_independent_review']).lower()}`", f"- **Aliases:** {', '.join(f'`/{x}`' for x in item['aliases'])}", f"- **Modes:** {', '.join(f'`{x}`' for x in item['supported_modes'])}", f"- **Terminal statuses:** {', '.join(f'`{x}`' for x in item['allowed_statuses'])}", ""]
        lines += ["### Arguments", "", "| Name | Type | Requirement | Description |", "|---|---|---|---|"]
        for arg in item.get("arguments", []):
            requirement = "required" if arg.get("required") else arg.get("requirement", "optional")
            description = arg.get("description", "")
            lines.append(f"| `{arg['name']}` | `{arg.get('type', 'string')}` | `{requirement}` | {description} |")
        if not item.get("arguments"):
            lines.append("| — | — | — | No arguments. |")
        lines += ["", "### Validation", ""] + bullets([f"**{x['id']}** (`{x['severity']}`): {x['description']}" for x in item["validation_rules"]])
        lines += ["", "### Orchestration", "", " → ".join(f"`{x}`" for x in item["orchestration_stages"]), ""]
        lines += ["### Agents and tools", ""]
        lines += [f"- **Agents:** {', '.join(f'`{x}`' for x in item.get('agent_ids', [])) or 'none'}", f"- **Tools:** {', '.join(f'`{x}`' for x in item.get('tool_ids', [])) or 'none'}", f"- **Permissions:** {', '.join(f'`{x}`' for x in item['permissions']) or 'none'}", ""]
        lines += ["### Side effects", ""] + json_block(item["side_effects"]) + [""]
        lines += ["### Errors", "", "| Code | Status | Meaning | Recovery |", "|---|---|---|---|"]
        for error in item["errors"]:
            lines.append(f"| `{error['code']}` | `{error['status']}` | {error['description']} | {error['recovery']} |")
        lines += ["", "### Examples", ""]
        for example in item["examples"]:
            lines += [f"#### {example['name']}", "", example.get("description", ""), ""] + json_block(example["input"]) + [f"Expected terminal status: `{example['expected_status']}`.", ""]
    return "\n".join(lines).rstrip() + "\n"


def tool_reference() -> str:
    lines = [
        "# SfSkills V2 evidence-tool reference",
        "",
        "Generated from `mcp/tool-specs/*.json`. Do not edit this file directly.",
        "",
        "These are normalized product evidence contracts, not unrestricted wrappers around Salesforce CLI, APIs, or upstream MCP servers.",
        "",
    ]
    for item in load_many("mcp/tool-specs"):
        lines += [f"## `{item['id']}`", "", item["purpose"], ""]
        lines += [
            f"- **Version:** `{item['version']}`",
            f"- **Operation:** `{item['operation_type']}`",
            f"- **Read-only:** `{str(item['read_only']).lower()}`",
            f"- **Explicit target pinning:** `{str(item['requires_target_pinning']).lower()}`",
            f"- **Unknown tool default:** `{item['unknown_tool_default']}`",
            f"- **Result schema:** `{item['result_schema']}`",
            f"- **Permissions:** {', '.join(f'`{x}`' for x in item['permission_classes'])}",
            f"- **Evidence types:** {', '.join(f'`{x}`' for x in item['evidence_types'])}",
            "",
        ]
        lines += ["### Arguments", "", "| Name | Type | Required | Description |", "|---|---|---:|---|"]
        for arg in item["arguments"]:
            lines.append(f"| `{arg['name']}` | `{arg.get('type', 'string')}` | {str(bool(arg.get('required'))).lower()} | {arg.get('description', '')} |")
        lines += ["", "### Normalization", ""] + bullets(item["normalization_rules"])
        lines += ["", "### Bounds and reliability", ""] + json_block({
            "pagination": item["pagination"],
            "timeout_seconds": item["timeout_seconds"],
            "retry_policy": item["retry_policy"],
            "rate_limit": item["rate_limit"],
            "cache_policy": item["cache_policy"],
        }) + [""]
        lines += ["### Security and audit", ""]
        lines += [f"- **Sensitive classes:** {', '.join(f'`{x}`' for x in item['sensitive_data_classes']) or 'none declared'}", f"- **Redaction profile:** `{item['redaction_profile']}`", f"- **Audit events:** {', '.join(f'`{x}`' for x in item['audit_events'])}", ""]
        lines += ["### Errors", "", "| Code | Tool status | Retryable | Meaning |", "|---|---|---:|---|"]
        for error in item["error_codes"]:
            lines.append(f"| `{error['code']}` | `{error['status']}` | {str(error['retryable']).lower()} | {error['description']} |")
        lines += ["", "### Required tests", ""] + bullets(item["required_tests"]) + [""]
        lines += ["### Upstream candidates", ""] + bullets(item["upstream_candidates"]) + [""]
    return "\n".join(lines).rstrip() + "\n"


def agent_reference() -> str:
    lines = [
        "# SfSkills V2 agent contract reference",
        "",
        "Generated from `agents/definitions/*.json`. Do not edit this file directly.",
        "",
        "Commands are the stable user surface. Agent exposure is deliberately smaller and host-dependent; machine contracts constrain authority even when a host renders the role differently.",
        "",
    ]
    for item in load_many("agents/definitions"):
        lines += [f"## `{item['id']}`", "", item["purpose"], ""]
        lines += [
            f"- **Kind:** `{item['kind']}`",
            f"- **Product:** `{item.get('product_id') or 'framework'}`",
            f"- **Recommended host exposure:** `{item['recommended_host_exposure']}`",
            f"- **Completion review required:** `{str(item['completion_review_required']).lower()}`",
            f"- **Permissions:** {', '.join(f'`{x}`' for x in item['permissions'])}",
            f"- **Tools in product contract:** {', '.join(f'`{x}`' for x in item.get('tool_ids', [])) or 'none'}",
            "",
        ]
        lines += ["### Inputs", "", item["inputs"], "", "### Outputs", "", item["outputs"], ""]
        lines += ["### Authority", ""] + json_block(item["authority_profile"]) + [""]
        lines += ["### Context", ""] + json_block(item["context_policy"]) + [""]
        lines += ["### Evidence required", ""] + bullets(item["evidence_required"]) + [""]
        lines += ["### Evidence prohibited", ""] + bullets(item["evidence_prohibited"]) + [""]
        lines += ["### Collaborators", ""] + bullets([f"`{x}`" for x in item["collaborators"]]) + [""]
        lines += ["### Failure modes", "", "| Code | Default status | Meaning |", "|---|---|---|"]
        for failure in item["failure_modes"]:
            lines.append(f"| `{failure['code']}` | `{failure['default_status']}` | {failure['description']} |")
        lines += ["", "### Success criteria", ""]
        success = item["success_criteria"] if isinstance(item["success_criteria"], list) else [x.strip() for x in str(item["success_criteria"]).split(";") if x.strip()]
        lines += bullets(success) + [""]
        lines += ["### Prompt principles", ""] + bullets(item["prompt_principles"]) + [""]
        lines += ["### Evaluation dimensions", ""] + bullets(item["evaluation_dimensions"]) + [""]
        lines += ["### Host exposure rationale", "", item["host_exposure_rationale"], "", "### Design notes", ""] + bullets(item["design_notes"]) + [""]
    return "\n".join(lines).rstrip() + "\n"


OUTPUTS = {
    ROOT / "commands/API_REFERENCE.md": command_reference,
    ROOT / "mcp/TOOL_REFERENCE.md": tool_reference,
    ROOT / "agents/CONTRACT_REFERENCE.md": agent_reference,
}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    drift: list[str] = []
    for path, builder in OUTPUTS.items():
        expected = builder()
        current = path.read_text(encoding="utf-8") if path.exists() else ""
        if current != expected:
            if args.check:
                drift.append(path.relative_to(ROOT).as_posix())
            else:
                path.write_text(expected, encoding="utf-8")
    if drift:
        print("Generated API reference drift:")
        for item in drift:
            print(f"  - {item}")
        return 1
    print("API references are current." if args.check else "API references generated.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
