#!/usr/bin/env python3
"""On-demand duplicate-skill audit.

Scores every candidate pair in the corpus (skills sharing a tag OR same
domain + shared trigger word) and writes the top-N to a markdown report.
Stdlib + ``pipelines/similarity.py`` only — no embeddings, no API calls.

Usage:
    python3 scripts/audit_duplicates.py
    python3 scripts/audit_duplicates.py --top 100
    python3 scripts/audit_duplicates.py --threshold 0.55
    python3 scripts/audit_duplicates.py --domain apex
    python3 scripts/audit_duplicates.py --json
    python3 scripts/audit_duplicates.py --full-scan      # skip the tag-prefilter

The report is written to ``docs/reports/duplicate-candidates.md`` (overwritten).
The intent is human review: each pair surfaces description, shared tags, and
shared trigger words so a reviewer can decide "merge", "rename", or "leave it".
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from pipelines.similarity import (  # noqa: E402
    DEFAULT_THRESHOLD,
    DEFAULT_WEIGHTS,
    SimilarityScore,
    SkillFingerprint,
    find_duplicate_pairs,
    fingerprint_corpus,
    load_threshold_from_config,
)


REPORT_PATH = ROOT / "docs" / "reports" / "duplicate-candidates.md"


def _filter_domain(fps: list[SkillFingerprint], domain: str | None) -> list[SkillFingerprint]:
    if not domain:
        return fps
    return [fp for fp in fps if fp.domain == domain]


def _format_pair_md(
    a: SkillFingerprint, b: SkillFingerprint, score: SimilarityScore, root: Path,
) -> str:
    a_rel = a.path.relative_to(root)
    b_rel = b.path.relative_to(root)
    shared_tags = ", ".join(score.shared_tags) or "—"
    shared_words = ", ".join(score.shared_trigger_words[:8]) or "—"
    return (
        f"### {a.skill_id}  ↔  {b.skill_id}  —  total {score.total:.3f}\n\n"
        f"- description ratio: **{score.description:.3f}**  ·  "
        f"tag jaccard: **{score.tags:.3f}**  ·  "
        f"trigger jaccard: **{score.triggers:.3f}**\n"
        f"- shared tags: {shared_tags}\n"
        f"- shared trigger words: {shared_words}\n"
        f"- files: [`{a_rel}`]({a_rel})  ·  [`{b_rel}`]({b_rel})\n\n"
        f"  > {a.skill_id}: {a.description}\n\n"
        f"  > {b.skill_id}: {b.description}\n"
    )


def _format_report(
    pairs: list[tuple[SkillFingerprint, SkillFingerprint, SimilarityScore]],
    threshold: float,
    elapsed_s: float,
    corpus_size: int,
    domain_filter: str | None,
    weights: dict[str, float],
    root: Path,
) -> str:
    header = (
        f"# Duplicate-skill audit — {date.today().isoformat()}\n\n"
        f"Generated by `scripts/audit_duplicates.py`. Pairs are scored by a\n"
        f"weighted combination of description similarity, tag-set Jaccard, and\n"
        f"trigger-word Jaccard. The threshold below is the minimum combined score\n"
        f"that surfaces a pair in this report.\n\n"
        f"- corpus size: **{corpus_size}** skills"
        f"{f' (filtered to domain `{domain_filter}`)' if domain_filter else ''}\n"
        f"- threshold: **{threshold:.2f}**\n"
        f"- weights: description={weights['description']:.2f}, "
        f"tags={weights['tags']:.2f}, triggers={weights['triggers']:.2f}\n"
        f"- pairs above threshold: **{len(pairs)}**\n"
        f"- scan duration: {elapsed_s:.1f} s\n\n"
        f"## Triage guide\n\n"
        f"For each pair below, decide one of:\n\n"
        f"1. **Merge** — fold both into one skill, delete the other.\n"
        f"2. **Rename / re-scope** — keep both but tighten descriptions and "
        f"`triggers:` so retrieval picks the right one.\n"
        f"3. **Leave it** — false positive (shared vocabulary, distinct purpose). "
        f"Note here so future audits don't re-surface it.\n\n"
        f"---\n\n"
    )

    if not pairs:
        return header + "_No pairs above threshold. The corpus is clean at this cutoff._\n"

    body = "\n".join(_format_pair_md(a, b, score, root) for a, b, score in pairs)
    return header + body


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Find near-duplicate skills across the corpus.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python3 scripts/audit_duplicates.py
  python3 scripts/audit_duplicates.py --top 100
  python3 scripts/audit_duplicates.py --threshold 0.55 --domain apex
  python3 scripts/audit_duplicates.py --json
        """,
    )
    parser.add_argument(
        "--top", type=int, default=50,
        help="Maximum pairs to include in the report (default 50). "
             "Pairs are sorted by combined score descending.",
    )
    parser.add_argument(
        "--threshold", type=float, default=None,
        help=f"Minimum combined score to surface a pair. "
             f"Default {DEFAULT_THRESHOLD} (overridable via "
             f"config/retrieval-config.yaml `duplicate_threshold.score`).",
    )
    parser.add_argument(
        "--domain", type=str, default=None,
        help="Restrict to a single domain (e.g. apex). Pairs across domains "
             "are still allowed if you don't pass this — both skills must be "
             "in the named domain when you do.",
    )
    parser.add_argument(
        "--full-scan", action="store_true",
        help="Skip the tag/domain prefilter and score every pair. "
             "Slower; use when you suspect the prefilter is missing duplicates "
             "(e.g. two skills with no shared tags but identical descriptions).",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Emit JSON to stdout instead of writing the markdown report.",
    )
    parser.add_argument(
        "--out", type=Path, default=REPORT_PATH,
        help=f"Where to write the markdown report (default {REPORT_PATH.relative_to(ROOT)}).",
    )
    args = parser.parse_args()

    threshold, weights = load_threshold_from_config(ROOT)
    if args.threshold is not None:
        threshold = args.threshold

    fps = fingerprint_corpus(ROOT)
    if args.domain:
        fps = _filter_domain(fps, args.domain)

    started = time.monotonic()
    pairs = find_duplicate_pairs(fps, threshold=threshold, weights=weights, full_scan=args.full_scan)
    elapsed = time.monotonic() - started

    pairs = pairs[: args.top]

    if args.json:
        payload = {
            "corpus_size": len(fps),
            "threshold": threshold,
            "weights": weights,
            "pair_count": len(pairs),
            "scan_duration_s": round(elapsed, 2),
            "pairs": [
                {
                    "a": {"id": a.skill_id, "path": str(a.path.relative_to(ROOT))},
                    "b": {"id": b.skill_id, "path": str(b.path.relative_to(ROOT))},
                    "score": {
                        "total": round(s.total, 4),
                        "description": round(s.description, 4),
                        "tags": round(s.tags, 4),
                        "triggers": round(s.triggers, 4),
                    },
                    "shared_tags": list(s.shared_tags),
                    "shared_trigger_words": list(s.shared_trigger_words),
                }
                for a, b, s in pairs
            ],
        }
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0

    report = _format_report(
        pairs, threshold=threshold, elapsed_s=elapsed,
        corpus_size=len(fps), domain_filter=args.domain,
        weights=weights, root=ROOT,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report, encoding="utf-8")

    print(f"Wrote {args.out.relative_to(ROOT)} — "
          f"{len(pairs)} pair(s) ≥ {threshold:.2f} from {len(fps)} skill(s) "
          f"in {elapsed:.1f}s.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
