#!/usr/bin/env python3
"""Build the native Cursor plugin package (bounded routers, not 1,034 rules).

Usage:
  python3 scripts/build_cursor_plugin.py
  python3 scripts/build_cursor_plugin.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "integrations" / "cursor"
DIST = ROOT / "dist" / "cursor" / "awesome-salesforce-skills"
MANIFEST = SRC / "build-manifest.json"

DOMAINS = [
    "admin",
    "agentforce",
    "apex",
    "architect",
    "data",
    "devops",
    "flow",
    "integration",
    "lwc",
    "omnistudio",
    "security",
]


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    h.update(path.read_bytes())
    return h.hexdigest()


def _copy_tree(src: Path, dest: Path) -> None:
    dest.parent.mkdir(parents=True, exist_ok=True)
    if src.is_dir():
        if dest.exists():
            shutil.rmtree(dest)
        shutil.copytree(src, dest)
    else:
        dest.write_bytes(src.read_bytes())


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def _top_router(registry: dict) -> str:
    counts = registry.get("domain_counts", {})
    total = registry.get("skill_count", 0)
    rows = "\n".join(
        f"| `{d}` | {counts.get(d, '?')} | `salesforce-{d}` |" for d in DOMAINS
    )
    return f"""---
name: salesforce
description: "Entry point for the SfSkills Cursor plugin. Bounded domain routers plus /triage-deployment, /triage-apex-tests, and MCP get_skill. Does not load 1,034 skill bodies. Not a Cursor Marketplace listing."
---

# Salesforce — SfSkills Cursor router

This plugin ships **bounded routers**, six focused subagents, `/triage-deployment`,
`/triage-apex-tests`, `/sfskills-doctor`, and the SfSkills MCP server. Detailed skill packages stay in
the SfSkills checkout and are loaded on demand via MCP `search_skill` / `get_skill`
or by opening `skills/<domain>/<slug>/SKILL.md` in that checkout.

**Generated by `scripts/build_cursor_plugin.py`. Do not hand-edit the copy under dist/.**

## Library size

{total} skill packages (roster only in this plugin):

| Domain | Skills | Router |
|---|---:|---|
{rows}

## How to find a skill

1. Open the domain router skill (`salesforce-devops`, …) and its `references/skill-index.md`.
2. If MCP is connected, call `search_skill`. A status of `index_missing` means bootstrap the checkout — it is not "no coverage".
3. Then `get_skill` for the package body.

## Product commands

- `/triage-deployment` — existing deploy job or local JSON fixture
- `/triage-apex-tests` — existing Apex test run (707…) or local JSON fixture
- `/sfskills-doctor` — install, CLI, index, aliases (no secrets)

## Rules

1. Do not load the full corpus.
2. Never deploy. Never guess a job ID.
3. Cite evidence IDs for material claims.
"""


def _domain_router(domain: str, count: int) -> str:
    return f"""---
name: salesforce-{domain}
description: "Router for SfSkills `{domain}` packages ({count}). Opens the roster; does not contain the guidance. Use MCP get_skill for the package body."
---

# Salesforce {domain} — domain router

**{count} packages.** Roster: `references/skill-index.md` in this skill folder.

**Generated by `scripts/build_cursor_plugin.py`. Do not hand-edit the copy under dist/.**

1. Find the slug in the roster.
2. Call MCP `get_skill` with id `{domain}/<slug>` or open the package in the SfSkills checkout.
3. Do not answer from this router file.
"""


def build(dest: Path) -> dict:
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True)

    plugin_dir = dest / ".cursor-plugin"
    plugin_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(SRC / "plugin.json", plugin_dir / "plugin.json")

    shutil.copy2(SRC / "mcp.json", dest / "mcp.json")
    _copy_tree(SRC / "hooks", dest / "hooks")
    _copy_tree(SRC / "scripts", dest / "scripts")
    _copy_tree(SRC / "agents", dest / "agents")
    _copy_tree(SRC / "commands", dest / "commands")

    registry = json.loads((ROOT / "registry" / "skills.json").read_text(encoding="utf-8"))
    counts = registry.get("domain_counts", {})

    salesforce_dir = dest / "skills" / "salesforce"
    _write(salesforce_dir / "SKILL.md", _top_router(registry))

    for domain in DOMAINS:
        skill_dir = dest / "skills" / f"salesforce-{domain}"
        _write(skill_dir / "SKILL.md", _domain_router(domain, int(counts.get(domain, 0))))
        src_index = ROOT / ".claude" / "skills" / f"salesforce-{domain}" / "references" / "skill-index.md"
        dest_index = skill_dir / "references" / "skill-index.md"
        dest_index.parent.mkdir(parents=True, exist_ok=True)
        if src_index.is_file():
            shutil.copy2(src_index, dest_index)
        else:
            _write(dest_index, f"# {domain} roster\n\nRun `python3 scripts/build_plugin.py` in the checkout to generate this roster.\n")

    # Make hook scripts executable on POSIX.
    for script in (dest / "hooks").glob("*.py"):
        script.chmod(script.stat().st_mode | 0o111)
    for script in (dest / "scripts").glob("*.py"):
        script.chmod(script.stat().st_mode | 0o111)

    _write(
        dest / "README.md",
        "\n".join(
            [
                "# awesome-salesforce-skills (Cursor plugin)",
                "",
                "Generated package. Install with `python3 scripts/install_cursor_plugin.py --link`.",
                "This is a **local** plugin. It is **not** listed on the Cursor Marketplace.",
                "License: PolyForm Small Business 1.0.0.",
                "",
            ]
        ),
    )

    files = []
    for path in sorted(dest.rglob("*")):
        if path.is_file():
            rel = path.relative_to(dest).as_posix()
            files.append({"path": rel, "sha256": _sha256_file(path)})
    return {"files": files, "count": len(files)}


def write_manifest(record: dict) -> None:
    MANIFEST.write_text(json.dumps(record, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def check() -> int:
    if not MANIFEST.is_file():
        print("ERROR: integrations/cursor/build-manifest.json missing. Run the builder once.", file=sys.stderr)
        return 1
    expected = json.loads(MANIFEST.read_text(encoding="utf-8"))
    tmp = ROOT / "dist" / "cursor" / ".check-awesome-salesforce-skills"
    try:
        actual = build(tmp)
    finally:
        if tmp.exists():
            shutil.rmtree(tmp)
    exp_map = {row["path"]: row["sha256"] for row in expected.get("files", [])}
    act_map = {row["path"]: row["sha256"] for row in actual["files"]}
    if exp_map != act_map:
        missing = sorted(set(exp_map) - set(act_map))
        extra = sorted(set(act_map) - set(exp_map))
        changed = sorted(p for p in exp_map.keys() & act_map.keys() if exp_map[p] != act_map[p])
        print("ERROR: Cursor plugin drift. Re-run python3 scripts/build_cursor_plugin.py", file=sys.stderr)
        if missing:
            print("  missing:", ", ".join(missing[:20]), file=sys.stderr)
        if extra:
            print("  extra:", ", ".join(extra[:20]), file=sys.stderr)
        if changed:
            print("  changed:", ", ".join(changed[:20]), file=sys.stderr)
        return 1
    print("Cursor plugin --check OK (%s files)" % actual["count"])
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the native SfSkills Cursor plugin")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    record = build(DIST)
    write_manifest(record)
    print(f"Wrote {DIST} ({record['count']} files)")
    print(f"Updated {MANIFEST.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
