#!/usr/bin/env python3
"""Generate docs/agents.md: the roster of every agent, grouped by class and tier.

Sources (all read-only):
  - agents/*/AGENT.md frontmatter: id, class, status, deprecated_in_favor_of
  - agents/*.md loader files: the slash command, when the tier docs do not carry one
  - agents/_shared/RUNTIME_VS_BUILD.md: tier membership, domain, one-line output
    and slash command (the same tier sections CLAUDE.md's "Run-time agents"
    section lists)

Frontmatter is canonical for class and status. An agent whose frontmatter says
``status: deprecated`` is always listed under Deprecated, whatever the tier docs
say. An agent present on disk but absent from the tier docs is listed under
"Unlisted" so the gap is visible instead of silent.

stdlib only. Usage:
    python3 scripts/generate_agent_roster.py          # write docs/agents.md
    python3 scripts/generate_agent_roster.py --check  # exit 1 if README is stale
    python3 scripts/generate_agent_roster.py --stdout
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AGENTS = ROOT / "agents"
TIER_DOC = AGENTS / "_shared" / "RUNTIME_VS_BUILD.md"
OUT = ROOT / "docs" / "agents.md"

HEADER = (
    "<!-- Generated by scripts/generate_agent_roster.py. Do not hand-edit; "
    "re-run the script. -->\n"
    "This roster is generated from `agents/*/AGENT.md` frontmatter and "
    "`agents/_shared/RUNTIME_VS_BUILD.md` by `python3 scripts/generate_agent_roster.py`.\n"
    "Edit those sources, not this file.\n"
)

# Section heading in RUNTIME_VS_BUILD.md -> (group key, display title)
TIERS = [
    ("build", "Build-time agents", "Build-time agents"),
    ("dev", "Developer + architecture tier", "Run-time: Developer + architecture"),
    ("t1", "Admin accelerators", "Run-time: Admin accelerators (Tier 1)"),
    ("t2", "Strategic", "Run-time: Strategic (Tier 2)"),
    ("t3", "Vertical + governance", "Run-time: Vertical + governance (Tier 3)"),
    ("t4", "Orchestration", "Run-time: Orchestration (Tier 4, beta)"),
    ("dep", "Deprecated", "Deprecated (redirect to audit-router)"),
]


def parse_frontmatter(path: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8")
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    fm: dict[str, str] = {}
    if not m:
        return fm
    for line in m.group(1).splitlines():
        km = re.match(r"([A-Za-z_][\w-]*):\s*(.*)$", line)
        if km:
            fm[km.group(1)] = km.group(2).strip().strip("\"'")
    return fm


def h1(path: Path) -> str:
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith("# "):
            return re.sub(r"\s+[—-]\s+DEPRECATED.*$", "", line[2:].strip())
    return ""


def loader_slash(agent_id: str) -> str:
    loader = AGENTS / f"{agent_id}.md"
    if not loader.exists():
        return ""
    m = re.search(r"(/[a-z][a-z0-9-]+):", loader.read_text(encoding="utf-8")[:600])
    return m.group(1) if m else ""


def parse_tier_doc() -> dict[str, dict[str, dict[str, str]]]:
    """Return {group_key: {agent_id: {domain, output, slash}}} from the tier doc."""
    text = TIER_DOC.read_text(encoding="utf-8")
    # Some rows were pasted onto one line ("... | `x` || `y` | ..."); split them.
    text = re.sub(r"\|\|\s*`", "|\n| `", text)
    out: dict[str, dict[str, dict[str, str]]] = {}
    current = None
    for line in text.splitlines():
        if line.startswith("#"):
            current = None
            for key, needle, _ in TIERS:
                if needle.lower() in line.lower():
                    current = key
                    out.setdefault(key, {})
                    break
            continue
        if current is None or not line.startswith("| `"):
            continue
        cells = [c.strip() for c in line.strip().strip("|").split("|")]
        aid = cells[0].strip("`")
        if current == "build" and len(cells) >= 2:
            out[current][aid] = {"domain": "", "output": cells[1], "slash": ""}
        elif current == "dep" and len(cells) >= 3:
            out[current][aid] = {
                "domain": "",
                "output": "Superseded by " + cells[2],
                "slash": cells[1].strip("`"),
            }
        elif len(cells) >= 4:
            out[current][aid] = {
                "domain": cells[1],
                "output": cells[2],
                "slash": cells[3].strip("`"),
            }
    return out


def esc(s: str) -> str:
    return s.replace("|", "\\|").strip()


def build() -> str:
    tiers = parse_tier_doc()
    agents: dict[str, dict[str, str]] = {}
    for md in sorted(AGENTS.glob("*/AGENT.md")):
        if md.parent.name.startswith("_"):
            continue
        fm = parse_frontmatter(md)
        fm.setdefault("id", md.parent.name)
        fm["title"] = h1(md)
        agents[fm["id"]] = fm

    placed: set[str] = set()
    sections: list[tuple[str, list[tuple[str, ...]], tuple[str, ...]]] = []

    for key, _needle, title in TIERS:
        rows: list[tuple[str, ...]] = []
        for aid, info in tiers.get(key, {}).items():
            fm = agents.get(aid)
            if fm is None:
                continue
            status = fm.get("status", "")
            is_dep = status == "deprecated"
            if (key == "dep") != is_dep:
                # frontmatter wins: deprecated agents belong only under Deprecated
                if is_dep and aid not in tiers.get("dep", {}):
                    info = dict(info)
                    tiers.setdefault("dep", {})[aid] = {
                        "domain": "",
                        "output": "Superseded by `"
                        + fm.get("deprecated_in_favor_of", "audit-router")
                        + "`",
                        "slash": info.get("slash", ""),
                    }
                continue
            if aid in placed:
                continue
            placed.add(aid)
            slash = info["slash"] or loader_slash(aid)
            if key == "build":
                rows.append((f"`{aid}`", status or "-", esc(info["output"])))
            elif key == "dep":
                rows.append(
                    (
                        f"`{aid}`",
                        f"`{slash}`" if slash else "-",
                        f"`{fm.get('deprecated_in_favor_of', 'audit-router')}`",
                    )
                )
            else:
                rows.append(
                    (
                        f"`{aid}`",
                        f"`{slash}`" if slash else "-",
                        esc(info["domain"]),
                        status or "-",
                        esc(info["output"]),
                    )
                )
        if key == "dep":
            # agents deprecated in frontmatter but missing from the doc's table
            for aid, fm in agents.items():
                if fm.get("status") == "deprecated" and aid not in placed:
                    placed.add(aid)
                    slash = tiers.get("dep", {}).get(aid, {}).get("slash") or loader_slash(aid)
                    rows.append(
                        (
                            f"`{aid}`",
                            f"`{slash}`" if slash else "-",
                            f"`{fm.get('deprecated_in_favor_of', 'audit-router')}`",
                        )
                    )
        if key == "build":
            hdr: tuple[str, ...] = ("Agent", "Status", "Role")
        elif key == "dep":
            hdr = ("Agent", "Deprecated slash command", "Superseded by")
        else:
            hdr = ("Agent", "Slash command", "Domain", "Status", "Primary output")
        sections.append((title, rows, hdr))

    unlisted = [aid for aid in agents if aid not in placed]
    if unlisted:
        rows = []
        for aid in sorted(unlisted):
            fm = agents[aid]
            slash = loader_slash(aid)
            rows.append(
                (
                    f"`{aid}`",
                    f"`{slash}`" if slash else "-",
                    fm.get("class", "-"),
                    fm.get("status", "-"),
                    esc(fm.get("title", "")),
                )
            )
        sections.append(
            ("Not in the tier docs", rows, ("Agent", "Slash command", "Class", "Status", "Title"))
        )

    total = len(agents)
    by_status: dict[str, int] = {}
    for fm in agents.values():
        k = f"{fm.get('class', '?')}/{fm.get('status', '?')}"
        by_status[k] = by_status.get(k, 0) + 1

    lines = ["# SfSkills agents", "", HEADER, ""]
    lines.append(
        f"{total} agent packages on disk. Frontmatter counts: "
        + ", ".join(f"{k} {v}" for k, v in sorted(by_status.items()))
        + ". Each one's playbook is `agents/<name>/AGENT.md`; slash commands are "
        "defined in `commands/`. No agent deploys to an org."
    )
    lines.append("")
    for title, rows, hdr in sections:
        if not rows:
            continue
        lines.append(f"## {title} ({len(rows)})")
        lines.append("")
        lines.append("| " + " | ".join(hdr) + " |")
        lines.append("|" + "|".join("---" for _ in hdr) + "|")
        for r in rows:
            lines.append("| " + " | ".join(r) + " |")
        lines.append("")
    lines.append(
        "Composite commands that span the orchestration loop rather than one agent: "
        "`/run-build` (one milestone) and `/build-from-requirements` (all stages, "
        "gate by gate)."
    )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if docs/agents.md is stale")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()
    content = build()
    if args.stdout:
        sys.stdout.write(content)
        return 0
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != content:
            print("docs/agents.md is stale; run scripts/generate_agent_roster.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
