#!/usr/bin/env python3
"""Generate ``docs/queue-progress.md`` — the human-readable queue dashboard.

Reads ``BACKLOG.yaml`` (the machine-readable queue) and the filesystem under
``skills/`` (authoritative for what's actually built) and produces a single
markdown file with:

  - status counts (TODO / RESEARCHED / IN_PROGRESS / DUPLICATE / BLOCKED / …)
  - drift between BACKLOG.yaml and disk (skills built but not in queue, and
    queue entries marked DONE-elsewhere with no matching skill folder)
  - oldest TODO and RESEARCHED entries by history age (proxies for staleness)
  - per-domain breakdown of pending work
  - the top of the queue (next 10 TODOs an agent should pick from)

Used by:

  - direct invocation: ``python3 scripts/generate_queue_dashboard.py``
  - the sync engine — regenerated on every ``skill_sync.py`` run, drift-checked
    by ``validate_repo.py``.
"""

from __future__ import annotations

import argparse
import sys
from collections import Counter, OrderedDict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from scripts.queue_reader import BacklogEntry, load_backlog  # noqa: E402

OUTPUT_PATH = ROOT / "docs" / "queue-progress.md"


def _filesystem_skills(root: Path) -> set[str]:
    """Set of every ``<domain>/<name>`` skill that exists on disk."""
    out: set[str] = set()
    for skill_md in (root / "skills").rglob("SKILL.md"):
        parts = skill_md.relative_to(root).parts
        # skills/<domain>/<name>/SKILL.md
        if len(parts) < 4:
            continue
        out.add(f"{parts[1]}/{parts[2]}")
    return out


def _filesystem_skill_names(root: Path) -> set[str]:
    """Set of just the skill *names* (no domain prefix). Used to detect
    queue entries whose skill exists in *some* domain — the queue often
    omits the domain column."""
    return {sid.split("/", 1)[1] for sid in _filesystem_skills(root)}


def _entries_by_status(entries: list[BacklogEntry]) -> dict[str, list[BacklogEntry]]:
    out: dict[str, list[BacklogEntry]] = {}
    for entry in entries:
        out.setdefault(entry.status or "(unset)", []).append(entry)
    return out


def _drift(entries: list[BacklogEntry], fs_skill_ids: set[str], fs_skill_names: set[str]) -> dict[str, list]:
    """Compute drift signals.

    queue_done_no_disk: entries the queue still says are pending whose skill
                       *already exists on disk*. Probably stale entries that
                       should be flipped to DUPLICATE or removed.
    disk_no_queue:     skills on disk that have no matching queue entry. The
                       queue is incomplete; that's expected — DONE rows were
                       deliberately dropped during migration. Only surface
                       here if an entry exists with a DIFFERENT status. We
                       don't list every disk skill, only mismatches.
    """
    queue_done_no_disk: list[dict] = []
    queue_pending_skills: set[str] = set()

    for entry in entries:
        if not entry.skill:
            continue
        queue_pending_skills.add(entry.skill)

        # If a queue entry is TODO/RESEARCHED but the skill folder already
        # exists somewhere, that's a drift signal.
        if entry.status in {"TODO", "RESEARCHED", "RESEARCH", "IN_PROGRESS"}:
            if entry.skill in fs_skill_names:
                queue_done_no_disk.append({
                    "id": entry.id,
                    "skill": entry.skill,
                    "queue_status": entry.status,
                })

    return {
        "queue_pending_but_skill_exists": queue_done_no_disk,
        "queue_pending_total": len(queue_pending_skills),
    }


def _format_date(history: list[dict]) -> str:
    if not history:
        return "—"
    last = history[-1].get("at", "")
    return last[:10] if last else "—"


def render_dashboard(
    entries: list[BacklogEntry],
    fs_skill_ids: set[str],
    fs_skill_names: set[str],
    today: str,
) -> str:
    by_status = _entries_by_status(entries)
    status_counts = OrderedDict()
    for status in ["TODO", "RESEARCHED", "RESEARCH", "IN_PROGRESS",
                   "DUPLICATE", "BLOCKED", "UPDATE", "SHIPPABLE"]:
        if status in by_status:
            status_counts[status] = len(by_status[status])

    drift = _drift(entries, fs_skill_ids, fs_skill_names)

    out: list[str] = []
    out.append(f"# Queue progress dashboard — {today}\n")
    out.append(
        "Generated by `scripts/generate_queue_dashboard.py`. **Do not hand-edit.**\n"
        "The drift check in `scripts/validate_repo.py` catches stale copies.\n"
    )
    out.append("")
    out.append(
        f"Backlog: **{len(entries)}** entries  ·  "
        f"Filesystem: **{len(fs_skill_ids)}** skills built  ·  "
        f"Last refresh: {today}"
    )
    out.append("")

    # Status table
    out.append("## By status")
    out.append("")
    out.append("| Status | Count | Notes |")
    out.append("|---|---:|---|")
    notes_by_status = {
        "TODO": "Not started; not yet researched.",
        "RESEARCHED": "Background notes captured; ready to build.",
        "IN_PROGRESS": "Claimed by an agent; do not pick up.",
        "DUPLICATE": "Already covered by an existing skill — kept for traceability.",
        "BLOCKED": "Stopped; check entry notes for the blocker.",
        "UPDATE": "Existing skill needs refresh.",
        "SHIPPABLE": "Ready for release / promotion.",
        "RESEARCH": "Investigation needed before deciding TODO vs DUPLICATE.",
    }
    for status, count in status_counts.items():
        out.append(f"| `{status}` | {count} | {notes_by_status.get(status, '—')} |")
    out.append("")

    # Per-domain breakdown
    domain_counts = Counter()
    for entry in entries:
        if entry.status not in {"TODO", "RESEARCHED", "RESEARCH", "IN_PROGRESS"}:
            continue
        domain_counts[entry.domain or "(uncategorized)"] += 1

    if domain_counts:
        out.append("## Pending work by domain")
        out.append("")
        out.append("Counts only entries in TODO / RESEARCHED / RESEARCH / IN_PROGRESS.")
        out.append("")
        out.append("| Domain | Pending |")
        out.append("|---|---:|")
        for domain, count in sorted(domain_counts.items(), key=lambda x: -x[1]):
            out.append(f"| `{domain}` | {count} |")
        out.append("")

    # Drift
    out.append("## Drift")
    out.append("")
    queue_pending_with_disk = drift["queue_pending_but_skill_exists"]
    if queue_pending_with_disk:
        out.append(
            f"**{len(queue_pending_with_disk)}** queue entries are still "
            "TODO/RESEARCHED/IN_PROGRESS but a skill with the same name already "
            "exists on disk. Either flip them to DUPLICATE (with a pointer to "
            "the existing skill) or remove the entry."
        )
        out.append("")
        out.append("| Entry id | Queue status | On disk as |")
        out.append("|---|---|---|")
        for d in queue_pending_with_disk[:50]:
            matches = sorted(s for s in fs_skill_ids if s.endswith("/" + d["skill"]))
            on_disk = ", ".join(f"`{m}`" for m in matches) or "—"
            out.append(f"| `{d['id']}` | {d['queue_status']} | {on_disk} |")
        if len(queue_pending_with_disk) > 50:
            out.append(f"| _… {len(queue_pending_with_disk) - 50} more not shown_ | | |")
        out.append("")
    else:
        out.append("No drift detected — every pending queue entry corresponds to a skill not yet on disk.")
        out.append("")

    # Top of the queue
    todos = [e for e in entries if e.status == "TODO"]
    researched = [e for e in entries if e.status == "RESEARCHED"]

    if researched or todos:
        out.append("## Pick next")
        out.append("")
        out.append(
            "Agents should prefer RESEARCHED (notes already captured) over plain "
            "TODO. The next 10 of each are listed below; for the full list run "
            "`python3 scripts/queue_reader.py --next --status RESEARCHED,TODO`."
        )
        out.append("")
        out.append("### RESEARCHED (preferred)")
        out.append("")
        if not researched:
            out.append("_None — every researched entry has been claimed or shipped._")
        else:
            out.append("| id | skill | domain | summary |")
            out.append("|---|---|---|---|")
            for e in researched[:10]:
                summary = (e.summary or "").replace("|", "\\|")
                if len(summary) > 100:
                    summary = summary[:99] + "…"
                out.append(f"| `{e.id}` | `{e.skill}` | `{e.domain or '?'}` | {summary} |")
        out.append("")

        out.append("### TODO")
        out.append("")
        if not todos:
            out.append("_Backlog clear._")
        else:
            out.append("| id | skill | domain | summary |")
            out.append("|---|---|---|---|")
            for e in todos[:10]:
                summary = (e.summary or "").replace("|", "\\|")
                if len(summary) > 100:
                    summary = summary[:99] + "…"
                out.append(f"| `{e.id}` | `{e.skill}` | `{e.domain or '?'}` | {summary} |")
        out.append("")

    # Recent activity
    activity = []
    for entry in entries:
        if entry.history:
            last = entry.history[-1]
            activity.append((last.get("at", ""), entry, last))
    activity.sort(reverse=True)
    if activity:
        out.append("## Recent activity")
        out.append("")
        out.append("Last 10 status transitions captured in `BACKLOG.yaml` `history`.")
        out.append("")
        out.append("| When | Entry | New status | Actor |")
        out.append("|---|---|---|---|")
        for at, entry, last in activity[:10]:
            out.append(
                f"| {at[:19]} | `{entry.id}` | "
                f"`{last.get('status', '?')}` | `{last.get('actor', '?')}` |"
            )
        out.append("")

    return "\n".join(out).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/queue-progress.md from BACKLOG.yaml.")
    parser.add_argument(
        "--check", action="store_true",
        help="Exit non-zero if the on-disk file differs from a fresh generation. Does not write.",
    )
    parser.add_argument(
        "--out", type=Path, default=OUTPUT_PATH,
        help=f"Where to write (default {OUTPUT_PATH.relative_to(ROOT)}).",
    )
    args = parser.parse_args()

    entries = load_backlog()
    fs_ids = _filesystem_skills(ROOT)
    fs_names = _filesystem_skill_names(ROOT)
    rendered = render_dashboard(entries, fs_ids, fs_names, today=date.today().isoformat())

    if args.check:
        if not args.out.exists() or args.out.read_text(encoding="utf-8") != rendered:
            print(f"DRIFT: {args.out.relative_to(ROOT)} is stale; "
                  "run `python3 scripts/generate_queue_dashboard.py`",
                  file=sys.stderr)
            return 1
        print(f"OK: {args.out.relative_to(ROOT)} is up-to-date.")
        return 0

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8")
    print(f"Wrote {args.out.relative_to(ROOT)} — {len(entries)} entries, {len(fs_ids)} on-disk skills.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
