#!/usr/bin/env python3
"""Structured reader/writer for ``BACKLOG.yaml``.

BACKLOG.yaml is the machine-readable queue. It replaces the row tables that
used to live inside ``MASTER_QUEUE.md``; the markdown file is now a short
prose intro that points here.

CLI surface preserved from the previous (markdown-backed) version so any
caller that automated against the old commands keeps working:

  - ``--list``           print every entry as JSONL
  - ``--next``           print the first entry whose status is in ``--status``
  - ``--status``         comma-separated eligible statuses for ``--next``
  - ``--set-status``     atomically update one entry's status and append to
                         its history (matched by ``--id``)
  - ``--id``             entry id (required for ``--set-status``)
  - ``--actor``          actor label recorded in history (required for ``--set-status``)
  - ``--summary``        aggregate status counts

Behavior changes vs. the old markdown reader:
  - Updates write to BACKLOG.yaml, not MASTER_QUEUE.md.
  - DONE state is no longer recorded here — the filesystem under ``skills/``
    is authoritative for "is this skill built?". The dashboard at
    ``docs/queue-progress.md`` reconciles the two.
  - The Notes column is replaced by a structured ``history`` list per entry;
    every ``--set-status`` appends ``{actor, status, at}`` to it.
"""

from __future__ import annotations

import argparse
import datetime
import json
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[1]
BACKLOG = ROOT / "BACKLOG.yaml"

# Recognized statuses. Same set as before; DONE is allowed for transitional
# updates but the dashboard ignores it (filesystem is authoritative).
STATUSES = {
    "TODO", "RESEARCHED", "RESEARCH", "IN_PROGRESS",
    "DONE", "DUPLICATE", "BLOCKED", "UPDATE", "SHIPPABLE",
}


@dataclass
class BacklogEntry:
    id: str
    status: str
    skill: str = ""
    domain: str | None = None
    role: str | None = None
    cloud: str | None = None
    summary: str | None = None
    notes: str | None = None
    source_line: int | None = None
    history: list[dict[str, str]] = field(default_factory=list)
    extra: dict[str, Any] = field(default_factory=dict)  # forward-compat

    @classmethod
    def from_dict(cls, raw: dict[str, Any]) -> BacklogEntry:
        known = {
            "id", "status", "skill", "domain", "role", "cloud",
            "summary", "notes", "source_line", "history",
        }
        extra = {k: v for k, v in raw.items() if k not in known}
        return cls(
            id=str(raw.get("id", "")),
            status=str(raw.get("status", "")),
            skill=str(raw.get("skill", "") or ""),
            domain=raw.get("domain"),
            role=raw.get("role"),
            cloud=raw.get("cloud"),
            summary=raw.get("summary"),
            notes=raw.get("notes"),
            source_line=raw.get("source_line"),
            history=list(raw.get("history") or []),
            extra=extra,
        )

    def to_dict(self) -> dict[str, Any]:
        out: dict[str, Any] = {"id": self.id, "status": self.status, "skill": self.skill}
        if self.domain is not None:
            out["domain"] = self.domain
        if self.role is not None:
            out["role"] = self.role
        if self.cloud is not None:
            out["cloud"] = self.cloud
        if self.summary is not None:
            out["summary"] = self.summary
        if self.notes is not None:
            out["notes"] = self.notes
        if self.source_line is not None:
            out["source_line"] = self.source_line
        out["history"] = list(self.history)
        out.update(self.extra)
        return out


def load_backlog(path: Path = BACKLOG) -> list[BacklogEntry]:
    if not path.exists():
        raise SystemExit(
            f"ERROR: {path} not found. "
            "Run scripts/_migrations/migrate_queue_to_yaml.py to create it."
        )
    raw = yaml.safe_load(path.read_text(encoding="utf-8")) or []
    if not isinstance(raw, list):
        raise SystemExit(f"ERROR: {path} top level must be a list, got {type(raw).__name__}")
    return [BacklogEntry.from_dict(item) for item in raw if isinstance(item, dict)]


def _yaml_quote(value: str) -> str:
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def render_backlog(entries: list[BacklogEntry]) -> str:
    """Render entries as the same hand-written YAML format the migration uses
    so the file's diff stays minimal across writes. We don't use
    ``yaml.safe_dump`` because its default style varies across PyYAML versions
    and we want the file format to be stable for git diffs."""
    out: list[str] = []
    out.append("# Generated by scripts/_migrations/migrate_queue_to_yaml.py.")
    out.append("# Re-run the migration to rebuild from MASTER_QUEUE.md, OR edit this")
    out.append("# file directly via scripts/queue_reader.py.")
    out.append("# See docs/QUEUE_FORMAT_PROPOSAL.md for the field shape.")
    out.append("")
    if not entries:
        out.append("[]")
        return "\n".join(out) + "\n"

    field_order = ["id", "status", "skill", "domain", "role", "cloud",
                   "summary", "notes", "source_line", "history"]

    for entry in entries:
        d = entry.to_dict()
        first = True
        for key in field_order:
            if key not in d:
                continue
            value = d[key]
            prefix = "- " if first else "  "
            first = False
            if isinstance(value, list):
                if not value:
                    out.append(f"{prefix}{key}: []")
                else:
                    out.append(f"{prefix}{key}:")
                    for item in value:
                        if isinstance(item, dict):
                            # Inline-style dict for history entries: keeps the
                            # file compact and grep-friendly.
                            inner = ", ".join(
                                f"{k}: {_yaml_quote(v)}" for k, v in item.items()
                            )
                            out.append(f"    - {{ {inner} }}")
                        else:
                            out.append(f"    - {_yaml_quote(item)}")
            elif isinstance(value, int):
                out.append(f"{prefix}{key}: {value}")
            else:
                out.append(f"{prefix}{key}: {_yaml_quote(value)}")
        # Forward-compat: emit any unrecognized keys at the bottom.
        for key, value in entry.extra.items():
            out.append(f"  {key}: {_yaml_quote(value)}")
    return "\n".join(out) + "\n"


def list_cmd(entries: list[BacklogEntry]) -> int:
    for entry in entries:
        print(json.dumps(entry.to_dict(), ensure_ascii=False, sort_keys=True))
    return 0


def next_cmd(entries: list[BacklogEntry], wanted: set[str]) -> int:
    for entry in entries:
        if entry.status in wanted:
            print(json.dumps(entry.to_dict(), ensure_ascii=False, sort_keys=True))
            return 0
    print(json.dumps({"error": "no entry matches", "wanted": sorted(wanted)}))
    return 1


def summary_cmd(entries: list[BacklogEntry]) -> int:
    counts: dict[str, int] = {}
    for entry in entries:
        counts[entry.status or "(unset)"] = counts.get(entry.status or "(unset)", 0) + 1
    print(f"Backlog entries: {len(entries)}")
    for status in sorted(counts):
        print(f"  {status:<14} {counts[status]}")
    return 0


def set_status_cmd(
    entries: list[BacklogEntry],
    entry_id: str,
    new_status: str,
    actor: str,
    *,
    backlog_path: Path = BACKLOG,
) -> int:
    if new_status not in STATUSES:
        print(f"ERROR: unknown status `{new_status}` — must be one of {sorted(STATUSES)}", file=sys.stderr)
        return 3
    candidates = [e for e in entries if e.id == entry_id]
    if not candidates:
        candidates = [e for e in entries if e.skill == entry_id]
    if not candidates:
        print(f"ERROR: no entry with id or skill `{entry_id}`", file=sys.stderr)
        return 2
    if len(candidates) > 1:
        print(
            f"ERROR: `{entry_id}` matches {len(candidates)} entries; pass a unique id",
            file=sys.stderr,
        )
        return 2
    target = candidates[0]
    now = datetime.datetime.now(datetime.timezone.utc).isoformat(timespec="seconds")
    target.history.append({"actor": actor, "status": new_status, "at": now})
    target.status = new_status

    backlog_path.write_text(render_backlog(entries), encoding="utf-8")
    print(json.dumps({"id": entry_id, "status": new_status, "actor": actor, "at": now}))
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--list", action="store_true")
    parser.add_argument("--next", action="store_true")
    parser.add_argument("--summary", action="store_true")
    parser.add_argument(
        "--status",
        type=str,
        default="TODO,RESEARCHED,RESEARCH,UPDATE",
        help="Comma-separated eligible statuses for --next",
    )
    parser.add_argument("--set-status", type=str, default=None)
    parser.add_argument("--id", type=str, default=None)
    parser.add_argument("--actor", type=str, default=None)
    args = parser.parse_args()

    entries = load_backlog()

    if args.summary:
        return summary_cmd(entries)
    if args.list:
        return list_cmd(entries)
    if args.next:
        wanted = {s.strip().upper() for s in args.status.split(",") if s.strip()}
        return next_cmd(entries, wanted)
    if args.set_status:
        if not args.id or not args.actor:
            print("ERROR: --set-status requires --id and --actor", file=sys.stderr)
            return 3
        return set_status_cmd(entries, args.id, args.set_status, args.actor)

    parser.print_help()
    return 3


if __name__ == "__main__":
    sys.exit(main())
