#!/usr/bin/env python3
"""Benchmark the sharded validator against a synthetic 500-skill corpus.

Wave-1 guardrail: if this bench regresses past 30 s wall-clock on local dev
hardware, the validator has fallen off the parallelization path and the
pre-commit hook will start hurting again. Wire into CI as a weekly job or
run manually before merging changes to ``scripts/validate_repo.py``.

We don't ship the synthetic skills — this script builds a throwaway repo
clone under ``/tmp`` (or the platform temp dir), seeds 500 minimal skill
folders, runs the validator against it with ``--skills-only --skip-drift``,
and tears everything down.

Why ``--skip-drift``: the synthetic repo has no registry/vector_index, so
the drift check would unconditionally fail. We're measuring the partition
+ worker-pool path, not the registry rebuild.

Why ``--skip-fixture-retrieval``: building a real lexical index over
synthetic skills inside the bench doubles its complexity for no signal —
retrieval quality is already tested by the real-repo validation run.
The bench only measures orchestration throughput (per-skill frontmatter +
structure + script ``--help`` fan-out + fixture coverage check).
"""

from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent


_MIN_SKILL_MD = """\
---
name: {name}
description: |
  Synthetic bench skill. Generated by scripts/validate_repo_bench.py.
  Triggers: {name} {category}
category: {category}
salesforce-version: "Spring '25+"
well-architected-pillars:
  - Security
tags:
  - bench
  - synthetic
triggers:
  - synthetic bench trigger
inputs:
  - input
outputs:
  - output
dependencies: []
version: 1.0.0
author: Bench
updated: 2026-04-16
---
# {display}

Synthetic bench content. Not shipped.

## Recommended Workflow

1. Step one.
2. Step two.
3. Step three.

## Official Sources Used

- [Salesforce Developer Docs](https://developer.salesforce.com/)
"""

_EMPTY_REF = "# Reference\n\nSynthetic.\n"


def _seed_skill(skill_dir: Path, category: str, name: str) -> None:
    """Write the minimum skill package the validator accepts."""
    skill_dir.mkdir(parents=True, exist_ok=True)
    (skill_dir / "SKILL.md").write_text(
        _MIN_SKILL_MD.format(name=name, category=category, display=name.replace("-", " ").title())
    )
    refs = skill_dir / "references"
    refs.mkdir(exist_ok=True)
    for f in ("examples.md", "gotchas.md", "well-architected.md", "llm-anti-patterns.md"):
        (refs / f).write_text(_EMPTY_REF)
    (skill_dir / "templates").mkdir(exist_ok=True)
    (skill_dir / "scripts").mkdir(exist_ok=True)


def _seed_corpus(repo: Path, count: int) -> list[tuple[str, str]]:
    """Seed ``count`` synthetic skills across a round-robin of domains.

    Returns the list of (category, name) tuples for fixture generation.
    """
    categories = [
        "admin", "apex", "lwc", "flow", "agentforce",
        "security", "integration", "data", "devops", "architect",
    ]
    seeded: list[tuple[str, str]] = []
    for i in range(count):
        cat = categories[i % len(categories)]
        name = f"bench-skill-{i:04d}"
        _seed_skill(repo / "skills" / cat / name, cat, name)
        seeded.append((cat, name))
    return seeded


def _seed_fixtures(repo: Path, seeded: list[tuple[str, str]]) -> None:
    """One fixture per seeded skill, so the fixture-coverage check passes.
    The queries are deliberately trivial; we're not benchmarking retrieval
    quality, just the orchestration loop."""
    (repo / "vector_index").mkdir(exist_ok=True)
    payload = {
        "queries": [
            {"query": name, "expected_skill": f"{cat}/{name}", "domain": cat, "top_k": 10}
            for cat, name in seeded
        ]
    }
    (repo / "vector_index" / "query-fixtures.json").write_text(json.dumps(payload))


def _seed_knowledge_stub(repo: Path) -> None:
    """Minimal knowledge/sources.yaml so load_sources_manifest doesn't trip."""
    (repo / "knowledge").mkdir(exist_ok=True)
    (repo / "knowledge" / "sources.yaml").write_text("sources: []\n")


def _seed_config_stub(repo: Path) -> None:
    """Mirror the repo's retrieval-config.yaml so search_knowledge can load."""
    (repo / "config").mkdir(exist_ok=True)
    (repo / "config" / "retrieval-config.yaml").write_text(
        "retrieval:\n  lexical_limit: 30\n  result_limit: 10\n  snippet_length: 220\n"
        "  min_skill_score: 0.0\n"
        "embeddings:\n  enabled: false\n  warn_threshold: 100000\n  require_threshold: 100000\n"
    )


def _seed_minimal_repo(repo: Path, count: int) -> None:
    """Copy the minimum repo infrastructure needed to run the validator."""
    # Python modules used by validate_repo.py.
    shutil.copytree(REPO / "pipelines", repo / "pipelines")
    shutil.copytree(REPO / "scripts", repo / "scripts")
    # Schemas the registry builder consults for validation.
    (repo / "config").mkdir(exist_ok=True)
    for f in (REPO / "config").glob("*.schema.json"):
        shutil.copy(f, repo / "config" / f.name)
    _seed_config_stub(repo)
    _seed_knowledge_stub(repo)
    # The actual bench skills.
    seeded = _seed_corpus(repo, count)
    _seed_fixtures(repo, seeded)


def _run_bench(count: int, threshold: float) -> tuple[bool, float, str]:
    """Seed ``count`` skills in a throwaway repo, run the validator with
    ``--skills-only --skip-drift --skip-fixture-retrieval``, and return
    ``(passed, wall_clock, output)``.

    ``passed`` is based SOLELY on wall-clock vs threshold. We expect
    the validator to report errors against our deliberately-minimal
    synthetic skills (they don't meet the repo's real strictness rules
    like 300-word minimum body, scope-exclusion in description, etc.).
    Correctness of those rules is tested by the real-repo validation
    run — this bench only measures orchestration throughput.
    """
    with tempfile.TemporaryDirectory(prefix="sfskills-bench-") as tmpdir:
        repo = Path(tmpdir)
        _seed_minimal_repo(repo, count)
        start = time.perf_counter()
        proc = subprocess.run(
            [sys.executable, str(repo / "scripts" / "validate_repo.py"),
             "--skills-only", "--skip-drift", "--skip-fixture-retrieval"],
            cwd=repo, capture_output=True, text=True,
        )
        elapsed = time.perf_counter() - start
        passed = elapsed < threshold
        output = proc.stdout + proc.stderr
        return passed, elapsed, output


def main() -> int:
    parser = argparse.ArgumentParser(description="Benchmark the sharded validator.")
    parser.add_argument("--count", type=int, default=500, help="Number of synthetic skills to seed (default 500).")
    parser.add_argument("--threshold", type=float, default=30.0, help="Wall-clock seconds the run must stay under (default 30).")
    parser.add_argument("--verbose", action="store_true", help="Print the validator's output even on success.")
    args = parser.parse_args()

    print(f"Seeding {args.count} synthetic skills in a temp repo...")
    passed, elapsed, output = _run_bench(args.count, args.threshold)
    verdict = "PASS" if passed else "FAIL"
    print(f"{verdict}: {args.count} skills validated in {elapsed:.2f}s (threshold {args.threshold:.1f}s)")
    if not passed or args.verbose:
        print("--- validator output ---")
        print(output)
    return 0 if passed else 1


if __name__ == "__main__":
    sys.exit(main())
