#!/usr/bin/env python3
"""Checker script for the Salesforce Surveys skill.

Scans a Salesforce metadata directory (plus the record-level artefacts this skill
produces) for survey configuration mistakes that deploy cleanly and then fail in
production:

  1. SurveySettings  -- settings/Survey.settings-meta.xml parses, uses the right
     root element, and has <enableSurvey>true</enableSurvey> whenever any other
     survey artefact is present in the tree.
  2. Guest user profiles -- object permissions for external survey respondents,
     and over-broad viewAllRecords / modifyAllRecords on survey objects.
  3. Flows -- record-triggered flows that create SurveyInvitation records without
     ParticipantId, and flows that write fields Salesforce derives and refuses.
  4. Survey design JSON -- surveys/*.survey.json design docs: every question has a
     valid type, every branch target resolves to a real page, and the
     anonymous/identified choice is consistent with guest access.
  5. Invitation CSV -- surveys/*.invitations.csv: required columns present, no
     non-createable columns, expiry parses and is in the future.

Grounding for every rule is cited inline against the Summer '26 / v62 PDF text.

Uses stdlib only -- no pip dependencies.

Usage:
    python3 check_salesforce_surveys.py --manifest-dir force-app/main/default
    python3 check_salesforce_surveys.py --manifest-dir force-app/main/default --warnings-as-errors

Exit codes:
    0  no errors
    1  one or more errors
    2  the manifest directory does not exist
"""

from __future__ import annotations

import argparse
import csv
import datetime as _dt
import json
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# ---------------------------------------------------------------------------
# Reference data, all grounded in the v62 guides.
# ---------------------------------------------------------------------------

# object_reference.txt L274965-274989 -- SurveyQuestion.QuestionType restricted picklist.
QUESTION_TYPES = {
    "Boolean",            # API v49.0+
    "CSAT",
    "Currency",
    "Date",
    "DateTime",
    "FreeText",
    "Image",
    "Matrix",             # API v55.0+
    "MultipleChoice",
    "MultiSelectPicklist",
    "NPS",
    "Number",
    "Picklist",
    "RadioButton",
    "StackRank",
    "Rating",
    "ShortText",          # API v49.0+
    "Slider",
    "Toggle",
}

# api_meta.txt L31309-31338 -- Metadata API SurveyQuestionType enum. Same domain,
# different spelling for the multiple-choice value; RadioButton is absent.
METADATA_ENUM_ONLY = {"MultiChoice"}

# Question types that carry a numeric answer in SurveyQuestionResponse.NumberValue
# (object_reference.txt L275217-275230).
NUMERIC_QUESTION_TYPES = {"NPS", "Rating", "Slider", "CSAT", "Number"}

# object_reference.txt L274594-274805 -- the only createable SurveyInvitation fields.
INVITATION_CREATEABLE = {
    "Name",
    "SurveyId",
    "ParticipantId",
    "CommunityId",
    "EmailBrandingId",
    "OwnerId",
    "IsDefault",
    "InviteExpiryDateTime",
    "OptionsAllowGuestUserResponse",
    "OptionsAllowParticipantAccessTheirResponse",
    "OptionsCollectAnonymousResponse",
}
INVITATION_REQUIRED = {"Name", "SurveyId"}

# Derived / read-only on SurveyInvitation: setting these fails at run time.
# ContactId/LeadId/UserId  object_reference.txt L274609, L274673, L274791
# InvitationLink           L274624-274631
# ResponseStatus           L274736-274783
INVITATION_DERIVED = {
    "ContactId": "derived from ParticipantId (object_reference.txt L274609)",
    "LeadId": "derived from ParticipantId (object_reference.txt L274673)",
    "UserId": "derived from ParticipantId (object_reference.txt L274791)",
    "InvitationLink": "generated by the platform (object_reference.txt L274624-274631)",
    "ResponseStatus": "read-only picklist (object_reference.txt L274736-274783)",
}

# SurveySubject: SurveyId and SubjectEntityType are derived
# (object_reference.txt L275987-275995, L275923-275926).
SUBJECT_DERIVED = {"SurveyId", "SubjectEntityType"}

SURVEY_OBJECTS = [
    "Survey",
    "SurveyInvitation",
    "SurveyResponse",
    "SurveyQuestionResponse",
    "SurveyQuestionScore",
    "SurveySubject",
]

REQUIRED_GUEST_PERMS = {
    "Survey": {"allowRead"},
    "SurveyInvitation": {"allowRead", "allowCreate"},
    "SurveyResponse": {"allowRead", "allowCreate"},
    "SurveyQuestionResponse": {"allowRead", "allowCreate"},
}


class Finding:
    """One issue. severity is 'ERROR' or 'WARN'."""

    __slots__ = ("severity", "where", "message")

    def __init__(self, severity: str, where: str, message: str) -> None:
        self.severity = severity
        self.where = where
        self.message = message

    def __str__(self) -> str:
        return f"{self.severity}: {self.where}: {self.message}"


# ---------------------------------------------------------------------------
# XML helpers.  NEVER use `elem.find(a) or elem.find(b)` -- a leaf Element is
# falsy in ElementTree, so an empty <allowRead/> would be treated as missing.
# ---------------------------------------------------------------------------


def _parse_xml(path: Path) -> ET.Element | None:
    """Parse XML and strip namespace prefixes so plain tag names match."""
    try:
        root = ET.parse(path).getroot()
    except (ET.ParseError, OSError):
        return None
    for elem in root.iter():
        if isinstance(elem.tag, str) and "}" in elem.tag:
            elem.tag = elem.tag.split("}", 1)[1]
    return root


def _child(parent: ET.Element, tag: str) -> ET.Element | None:
    """Return the first child with `tag`, or None. Explicit is-not-None test."""
    found = parent.find(tag)
    if found is not None:
        return found
    return None


def _text(parent: ET.Element | None, tag: str) -> str | None:
    """Text of the first `tag` child, stripped; None when absent or empty."""
    if parent is None:
        return None
    node = _child(parent, tag)
    if node is None:
        return None
    if node.text is None:
        return None
    value = node.text.strip()
    return value if value else None


def _is_true(parent: ET.Element, tag: str) -> bool:
    value = _text(parent, tag)
    return value is not None and value.lower() == "true"


# ---------------------------------------------------------------------------
# Check 1 -- SurveySettings
# ---------------------------------------------------------------------------


def _survey_artefacts_present(manifest_dir: Path, settings_path: Path | None) -> list[str]:
    """Evidence that this tree ships surveys, other than the settings file itself."""
    evidence: list[str] = []

    surveys_dir = manifest_dir / "surveys"
    if surveys_dir.is_dir():
        for pattern in ("*.survey.json", "*.invitations.csv"):
            for path in sorted(surveys_dir.glob(pattern)):
                evidence.append(str(path.relative_to(manifest_dir)))

    flow_dir = manifest_dir / "flows"
    if flow_dir.is_dir():
        for flow_path in sorted(flow_dir.glob("*.flow-meta.xml")):
            root = _parse_xml(flow_path)
            if root is None:
                continue
            process_type = _text(root, "processType")
            if process_type in ("Survey", "SurveyEnrich", "CustomerLifecycle"):
                evidence.append(str(flow_path.relative_to(manifest_dir)))
                continue
            for action in root.findall(".//actionCalls"):
                action_type = _text(action, "actionType")
                if action_type in (
                    "sendSurveyInvitation",
                    "dynamicSendSurveyInvitation",
                    "performSurveySentimentAnalysis",
                ):
                    evidence.append(str(flow_path.relative_to(manifest_dir)))
                    break

    bpg_dir = manifest_dir / "businessProcessGroups"
    if bpg_dir.is_dir():
        for path in sorted(bpg_dir.glob("*.businessProcessGroup-meta.xml")):
            evidence.append(str(path.relative_to(manifest_dir)))

    if settings_path is not None:
        settings_rel = str(settings_path.relative_to(manifest_dir))
        evidence = [e for e in evidence if e != settings_rel]
    return evidence


def check_survey_settings(manifest_dir: Path) -> list[Finding]:
    """SurveySettings parses and enables Surveys when survey artefacts are present.

    File name and location are fixed: "SurveySettings values are stored in a single
    file named Survey.settings in the settings folder" (api_meta.txt L127618-127620).
    enableSurvey defaults to false (L127641-127642).
    """
    findings: list[Finding] = []
    settings_dir = manifest_dir / "settings"

    candidates = []
    if settings_dir.is_dir():
        for name in ("Survey.settings-meta.xml", "Survey.settings"):
            path = settings_dir / name
            if path.is_file():
                candidates.append(path)

    settings_path = candidates[0] if candidates else None
    artefacts = _survey_artefacts_present(manifest_dir, settings_path)

    if settings_path is None:
        if artefacts:
            findings.append(
                Finding(
                    "ERROR",
                    "settings/Survey.settings-meta.xml",
                    "missing, but the tree ships survey artefacts ("
                    + ", ".join(artefacts[:3])
                    + ("..." if len(artefacts) > 3 else "")
                    + "). enableSurvey defaults to false (api_meta.txt L127641-127642), "
                    "so the target org will reject or ignore them.",
                )
            )
        return findings

    where = str(settings_path.relative_to(manifest_dir))
    root = _parse_xml(settings_path)
    if root is None:
        findings.append(Finding("ERROR", where, "is not well-formed XML."))
        return findings

    if root.tag != "SurveySettings":
        findings.append(
            Finding(
                "ERROR",
                where,
                f"root element is <{root.tag}>, expected <SurveySettings> "
                "(api_meta.txt L127650-127658).",
            )
        )
        return findings

    enable = _text(root, "enableSurvey")
    if enable is None:
        findings.append(
            Finding(
                "ERROR" if artefacts else "WARN",
                where,
                "has no <enableSurvey> element; it defaults to false "
                "(api_meta.txt L127641-127642).",
            )
        )
    elif enable.lower() != "true":
        findings.append(
            Finding(
                "ERROR" if artefacts else "WARN",
                where,
                f"<enableSurvey> is {enable!r}. Surveys is off in the target org, so "
                "every survey artefact in this package is inert.",
            )
        )

    if _is_true(root, "enableSurveyOwnerCanManageResponse"):
        findings.append(
            Finding(
                "WARN",
                where,
                "<enableSurveyOwnerCanManageResponse> is true. Survey owners can then "
                "manage participant responses; the documented default is false "
                "(api_meta.txt L127644-127646). Confirm this is intended.",
            )
        )

    # BusinessProcessGroup is gated on Customer Lifecycle Maps (api_meta.txt L31301).
    bpg_dir = manifest_dir / "businessProcessGroups"
    has_bpg = bpg_dir.is_dir() and any(bpg_dir.glob("*.businessProcessGroup-meta.xml"))
    if has_bpg and not _is_true(root, "enableIndustriesCxmEnabled"):
        findings.append(
            Finding(
                "ERROR",
                where,
                "ships BusinessProcessGroup metadata but <enableIndustriesCxmEnabled> is "
                "not true. That type 'is available in orgs with Surveys enabled with the "
                "Customer Lifecycle Designer license' (api_meta.txt L31301).",
            )
        )

    return findings


# ---------------------------------------------------------------------------
# Check 2 -- guest user profiles
# ---------------------------------------------------------------------------


def check_guest_user_profiles(manifest_dir: Path) -> list[Finding]:
    """Guest profiles grant the survey object permissions and nothing broader."""
    findings: list[Finding] = []
    profile_dir = manifest_dir / "profiles"
    if not profile_dir.is_dir():
        return findings

    guest_profiles = [
        path
        for path in sorted(profile_dir.glob("*.profile-meta.xml"))
        if "guest" in path.stem.lower()
    ]

    for profile_path in guest_profiles:
        where = str(profile_path.relative_to(manifest_dir))
        root = _parse_xml(profile_path)
        if root is None:
            findings.append(Finding("ERROR", where, "is not well-formed XML."))
            continue

        granted: dict[str, set[str]] = {}
        for obj_perm in root.findall(".//objectPermissions"):
            obj_name = _text(obj_perm, "object")
            if obj_name is None or obj_name not in SURVEY_OBJECTS:
                continue
            granted.setdefault(obj_name, set())
            for perm_tag in ("allowRead", "allowCreate", "allowEdit", "allowDelete"):
                if _is_true(obj_perm, perm_tag):
                    granted[obj_name].add(perm_tag)
            for broad in ("viewAllRecords", "modifyAllRecords"):
                if _is_true(obj_perm, broad):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"grants {broad} on {obj_name}. A guest profile must never hold "
                            "an all-records permission on survey data.",
                        )
                    )

        if not granted:
            continue  # profile does not touch survey objects at all

        for obj, required in REQUIRED_GUEST_PERMS.items():
            missing = required - granted.get(obj, set())
            if missing:
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"missing {', '.join(sorted(missing))} on {obj}. External survey "
                        "respondents fail silently on submit.",
                    )
                )

        if "allowCreate" in granted.get("Survey", set()):
            findings.append(
                Finding(
                    "WARN",
                    where,
                    "grants allowCreate on Survey. The Survey object has no create() call "
                    "(object_reference.txt L274221-274223), so this widens the audit "
                    "surface without enabling anything.",
                )
            )

    return findings


# ---------------------------------------------------------------------------
# Check 3 -- flows
# ---------------------------------------------------------------------------


def check_flow_survey_references(manifest_dir: Path) -> list[Finding]:
    """Flows that create SurveyInvitation / SurveySubject records write valid fields."""
    findings: list[Finding] = []
    flow_dir = manifest_dir / "flows"
    if not flow_dir.is_dir():
        return findings

    for flow_path in sorted(flow_dir.glob("*.flow-meta.xml")):
        where = str(flow_path.relative_to(manifest_dir))
        root = _parse_xml(flow_path)
        if root is None:
            continue

        if _text(root, "processType") in ("Survey", "SurveyEnrich"):
            continue  # the survey itself, not automation around it

        for record_create in root.findall(".//recordCreates"):
            obj_name = _text(record_create, "object")
            if obj_name not in ("SurveyInvitation", "SurveySubject"):
                continue

            element_name = _text(record_create, "name") or "(unnamed)"
            assigned = set()
            for assignment in record_create.findall(".//inputAssignments"):
                field = _text(assignment, "field")
                if field is not None:
                    assigned.add(field)

            if obj_name == "SurveyInvitation":
                for bad_field, reason in INVITATION_DERIVED.items():
                    if bad_field in assigned:
                        findings.append(
                            Finding(
                                "ERROR",
                                where,
                                f"element '{element_name}' sets SurveyInvitation.{bad_field}, "
                                f"which is not createable -- {reason}.",
                            )
                        )
                unknown = assigned - INVITATION_CREATEABLE - set(INVITATION_DERIVED)
                for field in sorted(unknown):
                    findings.append(
                        Finding(
                            "WARN",
                            where,
                            f"element '{element_name}' sets SurveyInvitation.{field}, which is "
                            "not in the documented createable field list "
                            "(object_reference.txt L274594-274805).",
                        )
                    )
                for field in sorted(INVITATION_REQUIRED - assigned):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"element '{element_name}' creates a SurveyInvitation without "
                            f"{field}.",
                        )
                    )
                if "ParticipantId" not in assigned:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"element '{element_name}' creates a SurveyInvitation without "
                            "ParticipantId. ParticipantId is the only writable participant "
                            "field and is not updateable "
                            "(object_reference.txt L274729-274742), so the response can "
                            "never be tied to the recipient.",
                        )
                    )

            else:  # SurveySubject
                for field in sorted(SUBJECT_DERIVED & assigned):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"element '{element_name}' sets SurveySubject.{field}, which "
                            "Salesforce derives and refuses on insert "
                            "(object_reference.txt L275987-275995, L275923-275926).",
                        )
                    )
                for field in sorted({"ParentId", "SubjectId"} - assigned):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"element '{element_name}' creates a SurveySubject without "
                            f"{field}. ParentId must be the SurveyInvitation or "
                            "SurveyResponse Id and SubjectId the business record "
                            "(object_reference.txt L275898-275917).",
                        )
                    )

        for action in root.findall(".//actionCalls"):
            if _text(action, "actionType") == "exportSurveyResponses":
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        "calls 'exportSurveyResponses', which the Metadata API guide lists "
                        "under 'These values are reserved for future use' "
                        "(api_meta.txt L69583-69586).",
                    )
                )

    return findings


# ---------------------------------------------------------------------------
# Check 4 -- survey design JSON
# ---------------------------------------------------------------------------


def _lint_survey_design(path: Path, where: str) -> list[Finding]:
    findings: list[Finding] = []
    try:
        design = json.loads(path.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        return [Finding("ERROR", where, f"is not valid JSON: {exc}")]

    if not isinstance(design, dict):
        return [Finding("ERROR", where, "top level must be a JSON object.")]

    survey_type = str(design.get("surveyType", "SURVEY")).upper()
    if survey_type not in ("SURVEY", "BASIC", "ASSESSMENT"):
        findings.append(
            Finding(
                "ERROR",
                where,
                f"surveyType {survey_type!r} is not one of SURVEY, BASIC, ASSESSMENT "
                "(object_reference.txt L274354-274359).",
            )
        )

    anonymous = bool(design.get("collectAnonymousResponse", False))
    allow_guest = bool(design.get("allowGuestUserResponse", False))
    allow_access = bool(design.get("allowParticipantsAccessTheirResponse", False))
    partial_save = bool(design.get("isPartialSaveEnabled", False))

    pages = design.get("pages")
    if not isinstance(pages, list) or not pages:
        return findings + [Finding("ERROR", where, "has no 'pages' array.")]

    page_names: list[str] = []
    for index, page in enumerate(pages):
        if not isinstance(page, dict):
            findings.append(Finding("ERROR", where, f"pages[{index}] is not an object."))
            continue
        name = page.get("name")
        if not name:
            findings.append(Finding("ERROR", where, f"pages[{index}] has no 'name'."))
            continue
        if name in page_names:
            findings.append(Finding("ERROR", where, f"duplicate page name {name!r}."))
        page_names.append(str(name))

    known_pages = set(page_names)

    for page in pages:
        if not isinstance(page, dict):
            continue
        page_name = str(page.get("name", "?"))
        questions = page.get("questions", [])
        if not isinstance(questions, list):
            findings.append(
                Finding("ERROR", where, f"page {page_name!r}: 'questions' must be a list.")
            )
            continue

        branching_questions = 0
        for question in questions:
            if not isinstance(question, dict):
                findings.append(
                    Finding("ERROR", where, f"page {page_name!r}: a question is not an object.")
                )
                continue
            q_name = str(question.get("name", "(unnamed)"))
            q_type = question.get("type")

            if q_type is None:
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"page {page_name!r}, question {q_name!r} has no 'type'.",
                    )
                )
            elif q_type in METADATA_ENUM_ONLY:
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"page {page_name!r}, question {q_name!r} uses {q_type!r}, the "
                        "Metadata API SurveyQuestionType spelling (api_meta.txt "
                        "L31309-31338). SurveyQuestion.QuestionType spells it "
                        "'MultipleChoice' (object_reference.txt L274965-274989).",
                    )
                )
            elif q_type not in QUESTION_TYPES:
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"page {page_name!r}, question {q_name!r} has type {q_type!r}, which "
                        "is not a SurveyQuestion.QuestionType value "
                        "(object_reference.txt L274965-274989).",
                    )
                )

            if "required" not in question:
                findings.append(
                    Finding(
                        "WARN",
                        where,
                        f"page {page_name!r}, question {q_name!r} does not state 'required'. "
                        "Whether a skip is possible changes how the response reads.",
                    )
                )

            branches = question.get("branches", [])
            if branches:
                branching_questions += 1
            if not isinstance(branches, list):
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"page {page_name!r}, question {q_name!r}: 'branches' must be a list.",
                    )
                )
                continue
            for branch in branches:
                if not isinstance(branch, dict):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"page {page_name!r}, question {q_name!r}: a branch is not an "
                            "object.",
                        )
                    )
                    continue
                target = branch.get("goToPage")
                if not target:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"page {page_name!r}, question {q_name!r}: a branch has no "
                            "'goToPage'.",
                        )
                    )
                elif str(target) not in known_pages:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"page {page_name!r}, question {q_name!r}: branch target "
                            f"{target!r} is not a page in this survey.",
                        )
                    )
                elif str(target) == page_name:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"page {page_name!r}, question {q_name!r}: branch targets its own "
                            "page, which loops the respondent.",
                        )
                    )

        if branching_questions and survey_type == "BASIC":
            findings.append(
                Finding(
                    "ERROR",
                    where,
                    f"page {page_name!r} defines branching, but surveyType is BASIC -- a "
                    "BASIC survey ships 'without inserted participant responses, display "
                    "logic, and page branching logic' "
                    "(object_reference.txt L274354-274359).",
                )
            )
        if branching_questions > 1:
            findings.append(
                Finding(
                    "ERROR",
                    where,
                    f"page {page_name!r} has {branching_questions} branching questions. "
                    "Routing is decided per page, so two questions on one page cannot send "
                    "the respondent to different places.",
                )
            )

    # Anonymity vs identity consistency.
    if anonymous and not allow_guest:
        findings.append(
            Finding(
                "WARN",
                where,
                "collectAnonymousResponse is true but allowGuestUserResponse is false. "
                "Anonymous collection normally implies unauthenticated respondents; "
                "confirm the audience.",
            )
        )
    if anonymous and design.get("associateSubjectRecord"):
        findings.append(
            Finding(
                "ERROR",
                where,
                "collectAnonymousResponse is true while associateSubjectRecord is set. "
                "An anonymous response cannot be traced to the participant, so the "
                "SurveySubject join gives a false sense of attribution.",
            )
        )
    if partial_save and (anonymous or allow_access):
        findings.append(
            Finding(
                "ERROR",
                where,
                "isPartialSaveEnabled is true, but Paused 'isn't available for invitations "
                "in which either OptionsAllowParticipantAccessTheirResponse or "
                "OptionsCollectAnonymousResponse is true' "
                "(object_reference.txt L274762-274766). Respondents cannot resume.",
            )
        )

    return findings


def check_survey_designs(manifest_dir: Path) -> list[Finding]:
    findings: list[Finding] = []
    surveys_dir = manifest_dir / "surveys"
    if not surveys_dir.is_dir():
        return findings
    for path in sorted(surveys_dir.glob("*.survey.json")):
        findings.extend(_lint_survey_design(path, str(path.relative_to(manifest_dir))))
    return findings


# ---------------------------------------------------------------------------
# Check 5 -- invitation CSV
# ---------------------------------------------------------------------------


def _parse_datetime(value: str) -> _dt.datetime | None:
    raw = value.strip()
    if not raw:
        return None
    if raw.endswith("Z"):
        raw = raw[:-1] + "+00:00"
    for parser in (
        lambda v: _dt.datetime.fromisoformat(v),
        lambda v: _dt.datetime.strptime(v, "%Y-%m-%d %H:%M:%S"),
        lambda v: _dt.datetime.strptime(v, "%Y-%m-%d"),
    ):
        try:
            parsed = parser(raw)
        except ValueError:
            continue
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=_dt.timezone.utc)
        return parsed
    return None


def check_invitation_csvs(manifest_dir: Path) -> list[Finding]:
    """SurveyInvitation load files use only createable columns with a future expiry."""
    findings: list[Finding] = []
    surveys_dir = manifest_dir / "surveys"
    if not surveys_dir.is_dir():
        return findings

    now = _dt.datetime.now(_dt.timezone.utc)

    for path in sorted(surveys_dir.glob("*.invitations.csv")):
        where = str(path.relative_to(manifest_dir))
        try:
            with path.open(newline="", encoding="utf-8-sig") as handle:
                reader = csv.DictReader(handle)
                headers = [h.strip() for h in (reader.fieldnames or [])]
                rows = list(reader)
        except (OSError, csv.Error) as exc:
            findings.append(Finding("ERROR", where, f"could not be read as CSV: {exc}"))
            continue

        if not headers:
            findings.append(Finding("ERROR", where, "has no header row."))
            continue

        for field in sorted(INVITATION_REQUIRED - set(headers)):
            findings.append(
                Finding(
                    "ERROR",
                    where,
                    f"missing required column {field!r} "
                    "(object_reference.txt L274594-274805).",
                )
            )
        if "ParticipantId" not in headers:
            findings.append(
                Finding(
                    "ERROR",
                    where,
                    "missing 'ParticipantId'. It is the only writable participant field and "
                    "cannot be added later -- it has Create but not Update "
                    "(object_reference.txt L274729-274742).",
                )
            )

        for header in headers:
            if header in INVITATION_DERIVED:
                findings.append(
                    Finding(
                        "ERROR",
                        where,
                        f"column {header!r} is not createable -- "
                        f"{INVITATION_DERIVED[header]}. The load will fail or drop it.",
                    )
                )
            elif header not in INVITATION_CREATEABLE:
                findings.append(
                    Finding(
                        "WARN",
                        where,
                        f"column {header!r} is not in the documented createable field list "
                        "for SurveyInvitation (object_reference.txt L274594-274805).",
                    )
                )

        if not rows:
            findings.append(Finding("WARN", where, "has a header but no data rows."))

        for line_no, row in enumerate(rows, start=2):
            for field in INVITATION_REQUIRED | {"ParticipantId"}:
                if field in headers and not (row.get(field) or "").strip():
                    findings.append(
                        Finding("ERROR", where, f"row {line_no}: {field} is blank.")
                    )

            expiry_raw = (row.get("InviteExpiryDateTime") or "").strip()
            if expiry_raw:
                expiry = _parse_datetime(expiry_raw)
                if expiry is None:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"row {line_no}: InviteExpiryDateTime {expiry_raw!r} is not a "
                            "parseable date-time.",
                        )
                    )
                elif expiry <= now:
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"row {line_no}: InviteExpiryDateTime {expiry_raw} is in the "
                            "past; the invitation is dead on arrival.",
                        )
                    )

            anon = (row.get("OptionsCollectAnonymousResponse") or "").strip().lower()
            access = (
                row.get("OptionsAllowParticipantAccessTheirResponse") or ""
            ).strip().lower()
            guest = (row.get("OptionsAllowGuestUserResponse") or "").strip().lower()

            for field, value in (
                ("OptionsCollectAnonymousResponse", anon),
                ("OptionsAllowParticipantAccessTheirResponse", access),
                ("OptionsAllowGuestUserResponse", guest),
                ("IsDefault", (row.get("IsDefault") or "").strip().lower()),
            ):
                if value and value not in ("true", "false"):
                    findings.append(
                        Finding(
                            "ERROR",
                            where,
                            f"row {line_no}: {field} is {value!r}; expected true or false.",
                        )
                    )

            if anon == "true" and (row.get("ParticipantId") or "").strip():
                findings.append(
                    Finding(
                        "WARN",
                        where,
                        f"row {line_no}: OptionsCollectAnonymousResponse is true while a "
                        "ParticipantId is supplied. The response will not be attributable, "
                        "and Paused is unavailable "
                        "(object_reference.txt L274762-274766).",
                    )
                )

    return findings


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def check_salesforce_surveys(manifest_dir: Path) -> list[Finding]:
    findings: list[Finding] = []
    findings.extend(check_survey_settings(manifest_dir))
    findings.extend(check_guest_user_profiles(manifest_dir))
    findings.extend(check_flow_survey_references(manifest_dir))
    findings.extend(check_survey_designs(manifest_dir))
    findings.extend(check_invitation_csvs(manifest_dir))
    return findings


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check Salesforce Surveys configuration and metadata for common issues.",
    )
    parser.add_argument(
        "--manifest-dir",
        default=".",
        help="Root of the Salesforce metadata directory (default: current directory).",
    )
    parser.add_argument(
        "--warnings-as-errors",
        action="store_true",
        help="Exit 1 when only warnings were found.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest_dir = Path(args.manifest_dir)

    if not manifest_dir.is_dir():
        print(f"ERROR: manifest directory not found: {manifest_dir}")
        return 2

    findings = check_salesforce_surveys(manifest_dir)
    errors = [f for f in findings if f.severity == "ERROR"]
    warnings = [f for f in findings if f.severity == "WARN"]

    for finding in findings:
        print(finding)

    print(f"\n{len(errors)} error(s), {len(warnings)} warning(s).")

    if errors:
        return 1
    if warnings and args.warnings_as_errors:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
